### PR TITLE
Fix backup removal in exit task and cleanup handling of URL mountpoints

### LINKED ISSUE #2611: ReaR configured with netfs backup can delete other/old folders on NFS at failure
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): Relax-and-Recover 2.4 / Git, according to code also current master and older versions since 1.18

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): CentOS Linux 7 (Core)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
BACKUP_URL=nfs://192.168.122.145/export/backup
BACKUP=NETFS
ISO_RECOVER_MODE=unattended
ISO_DEFAULT=automatic
NETFS_KEEP_OLD_BACKUP_COPY=yes
```
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): KVM guest

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): BIOS/GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): local disk

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift): trivial

* Description of the issue (ideally so that others can reproduce it):
In case of `NETFS_KEEP_OLD_BACKUP_COPY` ReaR can remove old backup (*.old) if interrupted during the `output` stage. If for any reason unmounting the NFS directory mounted at `outputfs` fails (for example, there is a process using this filesystem), ReaR proceeds to `rm -Rf -v /.../outputfs` as part of the exit tasks. This removes the old backup directory.
It will also destroy the backup directories for other machines, if multiple machines are configured to use the same NFS directory. A similar problem was reported as #465 and after being fixed it was reintroduced in a misguided "fix" (PR #782, 4e9c2a1b05f87762fb06355cf959b24eacc21f62) in ReaR 1.18.
There are multiple different copies of the exist task to cleanup the output directory in case of failure: those in the `prep` and `backup` stages look mostly safe (it would be still safer to use `rmdir` instead of `rm -Rf` though) and the only problematic one is in the `output` stage (usr/share/rear/output/default/100_mount_output_path.sh)

* Workaround, if any:
Probably configuring an `OUTPUT_URL` different from `BACKUP_URL` and not sharing the NFS directory among multiple machines would limit the damage (one would not lose backup data if using NETFS, only the output ISO).

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
```
+++ Print 'Running exit tasks'
+++ test 1
+++ echo -e 'Running exit tasks'
+++ local exit_task=
+++ for exit_task in '"${EXIT_TASKS[@]}"'
+++ Debug 'Exit task '\''umount -f -v '\''/tmp/rear.uUNE07AQyw2ey0S/outputfs'\'' >&2'\'''
+++ test 1
+++ Log 'Exit task '\''umount -f -v '\''/tmp/rear.uUNE07AQyw2ey0S/outputfs'\'' >&2'\'''
++++ date '+%Y-%m-%d %H:%M:%S.%N '
+++ local 'timestamp=2021-05-05 13:01:00.404599344 '
+++ test 1 -gt 0
+++ echo '2021-05-05 13:01:00.404599344 Exit task '\''umount -f -v '\''/tmp/rear.uUNE07AQyw2ey0S/outputfs'\'' >&2'\'''
2021-05-05 13:01:00.404599344 Exit task 'umount -f -v '/tmp/rear.uUNE07AQyw2ey0S/outputfs' >&2'
+++ eval 'umount -f -v '\''/tmp/rear.uUNE07AQyw2ey0S/outputfs'\'' >&2'
++++ umount -f -v /tmp/rear.uUNE07AQyw2ey0S/outputfs
umount.nfs4: /tmp/rear.uUNE07AQyw2ey0S/outputfs: device is busy
/tmp/rear.uUNE07AQyw2ey0S/outputfs: nfs4 mount point detected
/tmp/rear.uUNE07AQyw2ey0S/outputfs: umount failed
+++ for exit_task in '"${EXIT_TASKS[@]}"'
+++ Debug 'Exit task '\''rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs >&2'\'''
+++ test 1
+++ Log 'Exit task '\''rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs >&2'\'''
++++ date '+%Y-%m-%d %H:%M:%S.%N '
+++ local 'timestamp=2021-05-05 13:01:00.413623168 '
+++ test 1 -gt 0
+++ echo '2021-05-05 13:01:00.413623168 Exit task '\''rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs >&2'\'''
2021-05-05 13:01:00.413623168 Exit task 'rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs >&2'
+++ eval 'rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs >&2'
++++ rm -Rf -v /tmp/rear.uUNE07AQyw2ey0S/outputfs
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old/rear-localhost.iso'
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old/VERSION'
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old/README'
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old/rear-localhost.log'
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old/backup.tar.gz'
removed directory: '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost.old'
removed '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost/.lockfile'
removed directory: '/tmp/rear.uUNE07AQyw2ey0S/outputfs/localhost'
rm: cannot remove '/tmp/rear.uUNE07AQyw2ey0S/outputfs': Device or resource busy
+++ for exit_task in '"${EXIT_TASKS[@]}"'
+++ Debug 'Exit task '\''cleanup_build_area_and_end_program'\'''
+++ test 1
+++ Log 'Exit task '\''cleanup_build_area_and_end_program'\'''
++++ date '+%Y-%m-%d %H:%M:%S.%N '
+++ local 'timestamp=2021-05-05 13:01:00.439437963 '
+++ test 1 -gt 0
+++ echo '2021-05-05 13:01:00.439437963 Exit task '\''cleanup_build_area_and_end_program'\'''
2021-05-05 13:01:00.439437963 Exit task 'cleanup_build_area_and_end_program'
+++ eval cleanup_build_area_and_end_program
++++ cleanup_build_area_and_end_program
++++ Log 'Finished in 72 seconds'
+++++ date '+%Y-%m-%d %H:%M:%S.%N '
++++ local 'timestamp=2021-05-05 13:01:00.442303240 '
++++ test 1 -gt 0
++++ echo '2021-05-05 13:01:00.442303240 Finished in 72 seconds'
2021-05-05 13:01:00.442303240 Finished in 72 seconds
++++ test 1
++++ LogPrint 'You should also rm -Rf /tmp/rear.uUNE07AQyw2ey0S'
++++ Log 'You should also rm -Rf /tmp/rear.uUNE07AQyw2ey0S'
```
(The log message above also needs updating. If we are telling the user what to do, we should not instruct them to use a command that will destroy data. `rm -Rf --one-file-system` could help.)

### PR DESCRIPTION
**Pull request by pcahyna**
##### Pull Request Details:

* Type: **Bug Fix** / **Cleanup**

* Impact: **Critical**

* Reference to related issue (URL): #2611 #782 #465

* How was this pull request tested?
On CentOS 7 or CentOS 8:

  - backup and restore with backup on ISO and ISO stored on `OUTPUT_URL=sftp://`
  - backup to NFS with several reproducers for #2611 :
    - overriding `umount` by a function that does nothing and inserting a script that kills ReaR before unmounting URLs, thus triggering the exit tasks
      - both in backup and output stages (bug was present only in the output stage)
    - inserting a script that blocks umount by spawning a long running process with its cwd inside the temporary mountpoint `$BUILD_DIR/outputfs`
      - both in backup and output stages (bug was present only in the output stage)
    - overriding `umount` by a function that does nothing and returns an error
      - only in the output stage
  - backup to NFS without any bug reproducer
  - complete backup and restore with rsync over ssh (`BACKUP=RSYNC`)
  - backup to sshfs (`BACKUP=NETFS` `BACKUP_URL=sshfs://...`)
  - mkrescue with `OUTPUT=PXE` and several reproducers
    `PXE_TFTP_URL: nfs://...`, `PXE_CONFIG_URL: nfs://`. Reproducers consist of overriding `umount` by a function that does nothing and returns an error
    - before `800_copy_to_tftp.sh`
    - before `810_create_pxelinux_cfg.sh`
  - mkrescue with `OUTPUT=PXE` and no bug reproducer
    `PXE_TFTP_URL: nfs://...`, `PXE_CONFIG_URL: nfs://`

In the case of reproducers I chceked that other directories under the mountpoint do not get removed. In the case of no reproducers I checked that the proces completes successfully, and also that the build dir is correctly removed and that ReaR does not create and remove useless `$BUILD_DIR/outputfs` with URL schemes that do not need it (`rsync://`, `sftp://`).

* Brief description of the changes in this pull request:

Cleanup of temporary mount point handling, particularly for output. Unification of mount point umount and cleanup - move to the `mount_url()` and `umount_url()` functions, callers do not need to worry about it, resulting in huge deduplication (demultiplication), this concerns both the normal path and the error path (exit tasks). Replaced the various `rm -rf` of the mountpoint by `rmdir` (this fixes #2611) and added lazy umount in case normal umount does not succeed. If build dir is kept, propose a safe way to remove it to the user (`rm -Rf --one-file-system` instead of just `rm -Rf` where the user would risk to remove everything in their mounted filesystem if still mounted.)

Stop creating the empty mountpoint (`$BUILD_DIR/outputfs`) for schemes that do not need to mount anything (`rsync://` or anything "ftp-like".)

Fixes also some other bugs noted in the process: filesystem-specific umount command not called (https://github.com/rear/rear/commit/20359a987662cc0c3fcfa52d62d1feac7cd55850#r51319634) , unknown schemes considered invalid (noted in discussion under #932).

Identical scripts under `DUPLICITY` and `YUM` were replaced by symlinks to increase code sharing.

Reverts #782 (the change that introduced bug #2611) and #578 - it is not clear how .lockfile can exist in the unmounted filesystem, and if it does, it is a bug.

### CODE REVIEW

**Comment by pcahyna** [comment]
@N3WWN hello, please review the part that touches YUM (the second, third and fourth commit in the series).

**Comment by pcahyna** [comment]
During the work on this branch I have found many other issues that are not fixed in this PR (to keep the amount changes manageable). They are:

1. Unexpected use of `local` backup scheme in RBME: 5d85fc250232921bf314643e22b210b71996884f
2. Probably wrong symlink in BLOCKCLONE: PR #1172 , commit a4ab7406e653406c010c58a232f898d1ea85e592 @gozora 
3. Duplicate script in PXE: d850c4094238a03c9b926b88d7e1582ecd28af52
4. UEFI seems to have broken OBDR support: 41efc97eb7141c30455df45a871b98cd08e09fa7
5. OBDR probably got broken on ppc64le: 4ef0f30156f0afea4a02d12f40c2c9d18cbe5e43, PR #1383
6. `OUTPUT_MOUNTCMD` got broken by commit 6cd218ae30601eb56098b22581345f6ea8fe0aa2, see https://github.com/rear/rear/commit/20359a987662cc0c3fcfa52d62d1feac7cd55850#r51375233
7. `OUTPUT_UMOUNTCMD` is not called in exit tasks on error
8. Possible problems with `.lockfile`: PR #578 - what is `.lockfile` actually used for? What if `$OUTPUT_URL = $BACKUP_URL` but `$OUTPUT_PREFIX != $NETFS_PREFIX` ? What if `NETFS_KEEP_OLD_BACKUP_COPY` is set and `KEEP_OLD_OUTPUT_COPY` is unset? Also, it seems that `opath.old` created by a run that aborts will then be removed entirely by a subsequent run, because the lockfile will get removed by `150_save_copy_of_prefix_dir.sh`, resulting in no working backup. `backup/NETFS/default/250_create_lock.sh` claims that it "creates a lockfile in $NETFS_PREFIX to avoid that mkrescue overwrites ISO/LOGFILE made by a previous mkbackup run when the variable NETFS_KEEP_OLD_BACKUP_COPY has been set", but it is not clear how this gets achieved in the code.
9. backup log gets copied to `${opath}` even if `${opath}` is an empty string (can happen when backing up to a tape), resulting in dropping the log to the root directory: https://github.com/rear/rear/blob/2433c72f614af5b22547d6bd873ff4d224901a2c/usr/share/rear/backup/NETFS/default/500_make_backup.sh#L357
10. FDRUPSTREAM seems to copy a file to the output location when it is not mounted yet: #2142 @mutable-dan

**Comment by jsmeix** [comment]
@pcahyna 
thank you so much for that huge cleanup and severe bugfix work!

I will have a look as time permits but possibly it gets delayed until next week.

@gdha @rmetrich and all @rear/contributors 
I would much appreciate it if you find some time and have a look.
Perhaps you spot this or that issue by plain looking at the code?

Regarding "Impact: Urgent (Is Urgent higher than Critical?)"
Personally I think Urgent issues have higher timing priority than Critical issues
because Urgent means actual time pressure right now while Critical does not
necessarily imply time pressure but Critical could imply time pressure indirectly.
In this particular case I think the issue is Critical (because possible loss of data)
but not actually Urgent (because no current end-user case who has the issue).

**Comment by N3WWN** [comment]
> @N3WWN hello, please review the part that touches YUM (the second, third and fourth commit in the series).

@pcahyna LGTM!  I recall explicitly copying the files instead of using symlinks in case the files were still in a state of flux (the ZIPPER method was pretty new at the time) and I didn't want to force others to test the YUM method.  Now that these methods have been shown to be out of active change/development, I think it's safe to convert the files to symlinks.  Thanks!

**Comment by pcahyna** [comment]
@N3WWN thanks for the review. Note though that the symlinked files are not those copied from ZYPPER (those usually have some modifications, al least s/ZYPPER/YUM/), but from NETFS. It would be nice to share files between ZYPPER and YUM, but it would take more work.

**Comment by N3WWN** [comment]
> @N3WWN thanks for the review. Note though that the symlinked files are not those copied from ZYPPER (those usually have some modifications, al least s/ZYPPER/YUM/), but from NETFS. It would be nice to share files between ZYPPER and YUM, but it would take more work.

Yes, you're correct.  It's been a minute since I've really looked at the code, but still LGTM even after my mistaken reference ;)

**Review by gdha — APPROVED** [review]

**Comment by gdha** [comment]
@pcahyna  concerning OBDR - I cannot recall anyone ever used this (besides myself when I implemented this >10yrs ago and since then never used nor tested). I would even vote to remove this from ReaR (why maintaining if not used)?
Lots of changes - so we will see how these behave after a while ;-)
The problem with ReaR is/was it tries to do good for too many people without the needed backup/help from the community and then small mistakes creep in... It is good to clean up the code.
And for that a big kudo for @pcahyna  and @jsmeix

**Comment by pcahyna** [comment]
@gdha thank you for your review. Could you please have a look at the problems reported above, especially item 3. (apparently redundant script under PXE) and item 8. (intent of .lockfile)?

File: usr/share/rear/lib/global-functions.sh [hunk 1]
```diff
@@ -387,17 +432,33 @@ output_path() {
...
 ### Mount URL $1 at mountpoint $2[, with options $3]
-mount_url() {
+function mount_url() {
     local url=$1
     local mountpoint=$2
     local defaultoptions="rw,noatime"
     local options=${3:-"$defaultoptions"}
+    local scheme
+
+    scheme=$( url_scheme $url )
```
Comment (jsmeix) [inline usr/share/rear/lib/global-functions.sh:442]: Only out of curiosity:
Is there a special reason why `scheme` is assigned here
in a separated command and not directly via
```
local scheme=$( url_scheme $url )
```
like at other code places `local scheme=$( url_scheme $BACKUP_URL )`

File: usr/share/rear/lib/global-functions.sh [hunk 2]
```diff
@@ -558,65 +619,135 @@ mount_url() {
...
+### Unmount url $1 at mountpoint $2, perform mountpoint cleanup and exit task + error handling
+function umount_url() {
     local url=$1
     local mountpoint=$2
+    local scheme
 
-    case $(url_scheme $url) in
-        (null|tape|file|rsync|fish|ftp|ftps|hftp|http|https|sftp)
-            ### Don't need to umount anything for these
+    scheme=$( url_scheme $url )
```
Comment (jsmeix) [inline usr/share/rear/lib/global-functions.sh:646]: Same question as in https://github.com/rear/rear/pull/2625/files#r654244801

File: usr/share/rear/lib/global-functions.sh [hunk 3]
```diff
@@ -558,65 +619,135 @@ mount_url() {
...
+    esac
 
-            Log "Unmounting with '$umount_cmd'"
-            $umount_cmd
-            StopIfError "Unmounting failed."
+    # umount_url() is a wrapper that takes care of exit tasks and error handling and mountpoint cleanup.
+    # Therefore it also determines if exit task and mountpoint handling is required and returns early if not.
+    # The actual umount job is performed inside perform_umount_url().
+    # We do not request lazy umount here because we want umount errors to be reliably reported.
+    perform_umount_url $url $mountpoint || Error "Unmounting '$mountpoint' failed."
```
Comment (jsmeix) [inline usr/share/rear/lib/global-functions.sh:681]: I assume `perform_umount_url` is also called during "rear recover"
after the backup was restored but then we do not want to error out
so I wonder if here perhaps only a `LogPrintError` is sufficient?
Or do you like to keep the `Error` here and let me try to solve
the "error handling after the backup was restored" problem
in a more generic way for example as I described in
https://github.com/rear/rear/issues/2611#issuecomment-851456423

File: usr/share/rear/lib/global-functions.sh [hunk 4]
```diff
@@ -558,65 +619,135 @@ mount_url() {
...
+        else
+            # propagate errors from umount
+            return $retval
+        fi
+    fi
 }
 
-### Unmount mountpoint $1
-umount_mountpoint() {
+### Unmount mountpoint $1 [ lazily if $2 is nonempty ]
```
Comment (jsmeix) [inline usr/share/rear/lib/global-functions.sh:745]: I would prefer a more explicit syntax for the `$2` "lazy" parameter
because currently `perform_umount_url '$url' '$mountpoint' yes`
does not tell what that `yes` means so the code is less obvious
but even worse `perform_umount_url '$url' '$mountpoint' no`
is same as `perform_umount_url '$url' '$mountpoint' yes`
and that is really ugly - but matches well-known ugly C syntax
style like `if(!strcmp(str1, str2)) printf("strings are equal");`

More explicit syntax could be that `$2` must be either the exact word `lazy`
for lazy umount or empty for non-lazy umount so there might be even
a `BugError` in umount_mountpoint() if it was called with wrong `$2` value.

File: usr/share/rear/lib/framework-functions.sh [hunk 5]
```diff
@@ -140,15 +140,11 @@ function cleanup_build_area_and_end_program () {
...
             sleep 2
-            umount -f -l $BUILD_DIR/outputfs >&2
-            rm -Rf $v $BUILD_DIR/outputfs >&2
-        else
-            # not mounted so we can safely delete $BUILD_DIR/outputfs
-            rm -Rf $BUILD_DIR/outputfs
+            umount_mountpoint_lazy $BUILD_DIR/outputfs
         fi
-        rm -Rf $v $BUILD_DIR >&2
+        remove_temporary_mountpoint '$BUILD_DIR/outputfs' || BugError "Directory $BUILD_DIR/outputfs not empty, can not remove"
```
Comment (jsmeix) [inline usr/share/rear/lib/framework-functions.sh:146]: I think the Englisch spelling is always `cannot` (and never `can not`)
but I am not a native English speaker.

**Review by jsmeix — APPROVED** [review]
From plain looking at the changes all looks good to me.

The only place that I would like to have improved
(if possible with reasonable effort) is
a more explicit syntax for the $2 "lazy" parameter
of the `umount_mountpoint` function
but that is optional because this could be adapted later
because the relevant code is ReaR internal code.

File: usr/share/rear/lib/global-functions.sh (hunk 3 above)
Comment (pcahyna) [reply usr/share/rear/lib/global-functions.sh:681]: yes, I am aware of the problem, but it has existed before and solving it is outside the scope of this PR.

File: usr/share/rear/lib/framework-functions.sh (hunk 5 above)
Comment (pcahyna) [reply usr/share/rear/lib/framework-functions.sh:146]: https://en.wiktionary.org/wiki/cannot#Usage_notes , I can change it though

File: usr/share/rear/lib/global-functions.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/lib/global-functions.sh:442]: The reason is explained here: https://github.com/koalaman/shellcheck/wiki/SC2155

I did not want to change all current code places where `local foo=$(bar)` is used, but at the same time I did not want to introduce more instances of this suboptiomal idiom, so it resulted in some inconsistency between the current and added code.

File: usr/share/rear/lib/global-functions.sh [hunk 6]
```diff
@@ -558,65 +619,135 @@ mount_url() {
...
-    return 0
+### Helper which unmounts davfs mountpoint $1 and cleans up the cache,
+### performing lazy unmount if $2 is nonempty and normal unmount fails.
+function umount_davfs() {
+    local mountpoint=$1
+    local lazy="${2:-}"
+    if umount_mountpoint $mountpoint ; then
+        # Wait for 3 sek. then remove the cache-dir /var/cache/davfs
+        sleep 30
+        # ToDo: put in here the cache-dir from /etc/davfs2/davfs.conf
```
Comment (jsmeix) [inline usr/share/rear/lib/global-functions.sh:727]: Could you by the way change that `ToDo` into `TODO`
because at least my `vi` with its default settings
shows `TODO` (and `FIXME`) highlighted yellow
but no hightlighting for `ToDo` (or `FixMe`).

File: usr/share/rear/lib/global-functions.sh (hunk 1 above)
Comment (jsmeix) [reply usr/share/rear/lib/global-functions.sh:442]: Thank you for the explanation! I didn't know that.
So code like
```
local var=$(COMMAND) || Error "COMMAND failed"
```
won't work.
Fortunately is seems we don't have such code because
```
# find usr/share/rear -type f | xargs grep 'local .*||'
# find usr/share/rear -type f | xargs grep 'if .*local '
```
show no such code.

File: usr/share/rear/lib/global-functions.sh (hunk 3 above)
Comment (jsmeix) [reply usr/share/rear/lib/global-functions.sh:681]: Perfectly fine with me! Leave it as is.

File: usr/share/rear/lib/framework-functions.sh (hunk 5 above)
Comment (jsmeix) [reply usr/share/rear/lib/framework-functions.sh:146]: Again thanks for the explanation!
And again I learned something new.
Of course you can keep it as is.

File: usr/share/rear/lib/global-functions.sh (hunk 6 above)
Comment (pcahyna) [reply usr/share/rear/lib/global-functions.sh:727]: will do

File: usr/share/rear/lib/global-functions.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/lib/global-functions.sh:442]: yes, but it defeats the purpose of `set -e`. Compare
```bash
set -e
local foo=$(false)
```
and
```bash
set -e
local foo
foo=$(false)
```
(the second aborts, the first one does not).
I know that `set -e` probably won't work very well currently, so fixing this does not have a high priority.

**Comment by pcahyna** [comment]
I am going to push some commits to address what you have found and rebase. I will revert d850c4094238a03c9b926b88d7e1582ecd28af52 as well.

File: usr/share/rear/lib/global-functions.sh (hunk 1 above)
Comment (jsmeix) [reply usr/share/rear/lib/global-functions.sh:442]: Thank you for the explanation how `local var=$(COMMAND)` doesn't work with `set -e`!
I didn't have `set -e` in mind.
In general modal behaviour calls for troubles (one always forgets some unusual mode).

**Comment by jsmeix** [comment]
@pcahyna 
if you like you may do as a "by the way" addon in this pull request
https://github.com/rear/rear/pull/2608#issuecomment-832939131
https://github.com/rear/rear/pull/2608#issuecomment-834219708

**Comment by pcahyna** [comment]
@jsmeix all the updates pushed. If it looks ok, I will rebase one more time to squash a fixup commit into its ancestor and then you can merge the PR.

**Comment by pcahyna** [comment]
> concerning OBDR - I cannot recall anyone ever used this (besides myself when I implemented this >10yrs ago and since then never used nor tested). I would even vote to remove this from ReaR (why maintaining if not used)?

@gdha  Do new tape drives support OBDR, or is it something that HP dropped a long time ago? If it got dropped, I am for removing it. If it is still supported on reasonably modern hardware, I could try resurrecting it.

File: usr/share/rear/lib/global-functions.sh (hunk 4 above)
Comment (jsmeix) [reply usr/share/rear/lib/global-functions.sh]: Done via https://github.com/rear/rear/pull/2625/commits/6ddce251db788f04935c8fcb3ba74a826405b042
@pcahyna thank you!

File: usr/share/rear/lib/global-functions.sh (hunk 6 above)
Comment (jsmeix) [reply usr/share/rear/lib/global-functions.sh]: Done via
https://github.com/rear/rear/pull/2625/commits/22302c52d336db11937f384d85b838c165050308
@pcahyna thank you!

**Comment by jsmeix** [comment]
From plain looking at the changes all looks good to me
so @pcahyna you can repase and squash as you need.

**Comment by pcahyna** [comment]
rebase finished.

**Comment by jsmeix** [comment]
FYI regarding OBDR:
At SUSE we got in July 2018 a customer issue report about
```
ReaR OUTPUT=OBDR support missing for PPC64LE (needs to be implemented)
```
on SLES12 SP2 with SAP on PPC64LE using ReaR 1.18 which resulted
https://github.com/rear/rear/issues/1868

In our SUSE internal issue report I found this piece of information:
```
Tape drive is a IBM 7226 multimedia enclosure
It is not clear at this time if it supports OBDR ...
since 7226 multimedia enclosure seems
no function of OBDR(not sure)
```
but there was no further info whether or not that drive supports OBDR
or anything further how far OBDR actually worked for them, cf.
https://github.com/rear/rear/issues/1868#issuecomment-406592866

**Comment by pcahyna** [comment]
rebased again to fix a typo in commit message

**Comment by pcahyna** [comment]
I thought that OBDR was HP-specific, but maybe it got implemented by other vendors as well.

**Comment by jsmeix** [comment]
If there are no objections right now
I would like to merge it in about half an hour.

**Comment by jsmeix** [comment]
When OBDR is/was HP-specific it explains why IBM documents don't mention it.

**Comment by pcahyna** [comment]
I pushed again to fix another tiny commit message mistake, no functional difference.

**Comment by gdha** [comment]
@pcahyna Yes, OBDR is HPE specific - see the included PDF file.
> I thought that OBDR was HP-specific, but maybe it got implemented by other vendors as well.

[Compatibility_Matrices.pdf](https://github.com/rear/rear/files/6676977/Compatibility_Matrices.pdf)

That being said we never got a complaint it was working (and I'm pretty sure it is broken in the meantime) - IMHO I'm in favor of removing it altogether. @dagwieers Do you mind if it was gone as you were the only one ever used by my knowledge?

**Comment by jsmeix** [comment]
@pcahyna 
again many thanks for your huge bugfix and cleanup work!

I wish you and all ReaR contributors and users
a relaxed and recoverying weekend!
