### PR TITLE
Refactor rsync URL support, fixes rsync OUTPUT_URL

### LINKED ISSUE #2781: Missing /usr/share/rear/output/PXE/default/820_copy_to_net.sh and PXE output fails with rsync protocol - DRLM issue 189
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.6

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): RHEL 8.5

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): DRLM managed

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): PowerVM LPAR

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): ppc64le

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): SAN

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

The initrd and kernel files of the PXE ouput are not being copied properly on OUTPUT_PREFIX using RSYNC

* Workaround, if any:

put back the /usr/share/rear/output/PXE/default/820_copy_to_net.sh in place to do it properly

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

see: https://github.com/brainupdaters/drlm/issues/189

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

### PR DESCRIPTION
**Pull request by pcahyna**
##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): closes #2781 

* How was this pull request tested?
  - recovery using `OUTPUT=USB` `BACKUP=RSYNC` with a `rsync://...:/...` (rsync over ssh) and `rsync://...::/...` (rsyncd) `BACKUP_URL`
  - recovery using `OUTPUT=ISO` `BACKUP=RSYNC` with a `rsync://...:/...` (rsync over ssh) `BACKUP_URL` and three values of `OUTPUT_URL`:  `rsync://...:/...` (rsync over ssh) but different from `BACKUP_URL`, `rsync://...::/...` (rsyncd), and undefined (to inherit  `BACKUP_URL`). Verified that the output ISO is found at the right places on the rsync server.
  - mkrescue and mkbackuponly to localhost with a `rsync://...:/...` (rsync over ssh) `BACKUP_URL` and `OUTPUT_URL`, the latter pointing to a different directory than the former. Verified that after `mkrescue` the ISO is under `OUTPUT_URL` and not `BACKUP_URL`.

* Brief description of the changes in this pull request:

The code to parse `rsync://` URLs was `BACKUP_URL` specific.
If one specified `BACKUP=RSYNC` and an `OUTPUT_URL` different from `BACKUP_URL`,
the `OUTPUT_URL` was ignored and the output files went to `BACKUP_URL`.

Fix by introducing generic functions for rsync URL parsing and
use them for both `BACKUP_URL` and `OUTPUT_URL`, as appropriate.
Replace all uses of global RSYNC_* variables derived
from `BACKUP_URL` by those functions.

### CODE REVIEW

File: usr/share/rear/lib/rsync-functions.sh [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+# BACKUP_URL=rsync://[USER@]HOST[:PORT]/PATH    # using rsync (is not compatible with new style!!!)
+
+#### NEW STYLE:
+# BACKUP_URL=rsync://[USER@]HOST[:PORT]/PATH    # using ssh
+# BACKUP_URL=rsync://[USER@]HOST[:PORT]::/PATH  # using rsync
+
+function rsync_validate () {
+    local url="$1"
+
+    if [[ "$(url_scheme "$url")" != "rsync" ]]; then # url_scheme still recognizes old style
```
Comment (jsmeix) [inline usr/share/rear/lib/rsync-functions.sh:17]: Could you also update the comment in the
url_scheme() function to
```
    # rsync scheme does not have to start with rsync:// it can also be scp style
    # see the comments in usr/share/rear/lib/rsync-functions.sh
```

File: usr/share/rear/lib/rsync-functions.sh [hunk 2]
```diff
@@ -0,0 +1,163 @@
...
+        (ssh)
+            echo "$path"
+            ;;
+
+    esac
+}
+
+function rsync_port () {
+    # XXX changing port not implemented yet
+    echo 873
```
Comment (jsmeix) [inline usr/share/rear/lib/rsync-functions.sh:102]: Caution!
Regardless that RSYNC_PORT is not documented in default.conf
it might be used by users who inspected the code and found it
in usr/share/rear/prep/RSYNC/default/100_check_rsync.sh
so I suggest to use something like
```
function rsync_port () {
    # Regardless that RSYNC_PORT is not documented in default.conf
    # it might be used by users who inspected the code up to ReaR 2.6
    # where RSYNC_PORT was used in prep/RSYNC/default/100_check_rsync.sh
    # (873 is the default port of rsync server):
    is_positive_integer $RSYNC_PORT && echo $RSYNC_PORT || echo 873
}
```
or - perhaps even better - we document RSYNC_PORT
officially in default.conf ?

**Comment by jsmeix** [comment]
@pcahyna 
thank you very much for that major cleanup!

Could you please provide me a summary of the advantages
but also the possibly backward incompatible changes
that could happen because of this cleanup?

I would like to add that summary to the
"New features, bigger enhancements, and possibly backward incompatible changes"
section in the ReaR 2.7 release notes which are currently at
https://github.com/rear/rear.github.com/blob/jsmeix-release-notes-2-7/documentation/release-notes-2-7.md

File: usr/share/rear/lib/rsync-functions.sh (hunk 2 above)
Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:102]: This line comes from here: https://github.com/rear/rear/pull/2831/files#diff-e625ae03f11218c80d8b5a4b0f00017895f41de9c6139a12783cd60142df31c7L32 . Note that in the old version of the code, the number was also hardcoded and was not a user-settable parameter. So, the behavior has not changed and it should not become a parameter now. I would prefer to leave a proper implementation of PORT to another PR.

File: usr/share/rear/lib/rsync-functions.sh [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+
+#### NEW STYLE:
+# BACKUP_URL=rsync://[USER@]HOST[:PORT]/PATH    # using ssh
+# BACKUP_URL=rsync://[USER@]HOST[:PORT]::/PATH  # using rsync
+
+function rsync_validate () {
+    local url="$1"
+
+    if [[ "$(url_scheme "$url")" != "rsync" ]]; then # url_scheme still recognizes old style
+        Error "Non-rsync URL $url !"
```
[the remark this answers is not in the document]
Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:18]: yes, the idea is that one should not call `rsync_` functions on a non-rsync URL.

**Comment by pcahyna** [comment]
During the work on this PR I have found many other anomalies in the rsync code, most of them are left untouched.
* the handling of `rsync` output URL scheme is under RSYNC (https://github.com/rear/rear/tree/master/usr/share/rear/output/RSYNC/default), which is a backup method, despite the output URL being in principle independent from backup method. This leads to different code being executed for `OUTPUT_URL=rsync://` depending on whether `BACKUP=RSYNC` or not. (If not, the output is handled in `950_copy_result_files.sh`, which seems to handle the URL differently: https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/output/default/950_copy_result_files.sh#L131 )
  * as a consequence, if `BACKUP=RSYNC`, the structure of the output files at a `rsync://` location is different. In other cases, `RSYNC_PREFIX` is not respected, but in case of `BACKUP=RSYNC`, `RSYNC_PREFIX` is respected. See https://github.com/rear/rear/issues/2781#issuecomment-1160172273 for details.
* Creation of the `backup` prefix directory happens in the `output` stage (https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh#L6). If `backup` is executed without `output` (by running `rear mkbackuponly`), it crashes, because the prefix directory does not exist. (This one is fixed in the PR.)
* `BACKUP_RSYNC_OPTIONS` inconsistencies between rsync-over-ssh and rsyncd cases. For rsyncd, they are always added to rsync options, for ssh only when creating the backup. The former actually leads to a bug, where `--relative` gets added to `BACKUP_RSYNC_OPTIONS` and then `.autorelabel` becomes a directory (in https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh#L25), leading to selinux relabeling not working (I had to fix SELinux manually in my tests).
* Some places seem to assume ssh access unconditionally, especially 500_make_rsync_backup.sh (see the `check_remote_df`, `check_remote_du` functions). One instance of similar code got removed in #2797.
* There is detection of xattr support on the remote server (using ssh access) https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh#L43, but this does not seem to work: in `cd ${path} && touch .is_xattr_supported && setfattr -n user.comment -v 'File created by ReaR to test if this filesystems suppor extended attributes.' .is_xattr_supported && getfattr -n user.comment .is_xattr_supported 1>/dev/null; find .is_xattr_supported -empty -delete`, the last `find` clobbers the exit status.

File: usr/share/rear/lib/rsync-functions.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:17]: Good catch. This made me test the "scp-style", and also the alternative old-style rsync url (with double `::` and no `rsync://` prefix). Both work.

**Comment by pcahyna** [comment]
During the work on this PR I have found many other anomalies in the rsync code, most of them are left untouched.
* the handling of `rsync` output URL scheme is under RSYNC (https://github.com/rear/rear/tree/master/usr/share/rear/output/RSYNC/default), which is a backup method, despite the output URL being in principle independent from backup method. This leads to different code being executed for `OUTPUT_URL=rsync://` depending on whether `BACKUP=RSYNC` or not. (If not, the output is handled in `950_copy_result_files.sh`, which seems to handle the URL differently: https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/output/default/950_copy_result_files.sh#L131 )
  * as a consequence, if `BACKUP=RSYNC`, the structure of the output files at a `rsync://` location is different. In other cases, `RSYNC_PREFIX` is not respected, but in case of `BACKUP=RSYNC`, `RSYNC_PREFIX` is respected. See https://github.com/rear/rear/issues/2781#issuecomment-1160172273 for details.
* Creation of the `backup` prefix directory happens in the `output` stage (https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/output/RSYNC/default/200_make_prefix_dir.sh#L6). If `backup` is executed without `output` (by running `rear mkbackuponly`), it crashes, because the prefix directory does not exist. (This one is fixed in the PR.)
* `BACKUP_RSYNC_OPTIONS` inconsistencies between rsync-over-ssh and rsyncd cases. For rsyncd, they are always added to rsync options, for ssh only when creating the backup. The former actually leads to a bug, where `--relative` gets added to `BACKUP_RSYNC_OPTIONS` and then `.autorelabel` becomes a directory (in https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh#L25), leading to selinux relabeling not working (I had to fix SELinux manually in my tests).
* Some places seem to assume ssh access unconditionally, especially 500_make_rsync_backup.sh (see the `check_remote_df`, `check_remote_du` functions). One instance of similar code got removed in #2797.
* There is detection of xattr support on the remote server (using ssh access) https://github.com/rear/rear/blob/8b8ad86c71eaea0ad03d64f5892e3f37d797a5e0/usr/share/rear/prep/RSYNC/default/150_check_rsync_protocol_version.sh#L43, but this does not seem to work: in `cd ${path} && touch .is_xattr_supported && setfattr -n user.comment -v 'File created by ReaR to test if this filesystems suppor extended attributes.' .is_xattr_supported && getfattr -n user.comment .is_xattr_supported 1>/dev/null; find .is_xattr_supported -empty -delete`, the last `find` clobbers the exit status.

> Could you please provide me a summary of the advantages
> but also the possibly backward incompatible changes
> that could happen because of this cleanup?

I suppose you are interested in changes since 2.6, that it this change and the change that triggered #2781 combined. Ok, I will provide a summary.

**Comment by pcahyna** [comment]
@jsmeix  "Rsync OUTPUT_URLs are now properly supported with `BACKUP=RSYNC`. Previously the output went to the location specified by `BACKUP_URL` and `OUTPUT_URL` was ignored. One exception was `OUTPUT=PXE`, where the output was uploaded to `OUTPUT_URL` in addition to `BACKUP_URL`, but `RSYNC_PREFIX` was not respected and the interpretation of the URL was different - an URL of the form `rsync://[USER@]HOST[:PORT]/PATH` was interpreted as using the rsync protocol, while in all other cases such URL would be interpreted as using rsync over ssh. This special handling is now removed - a rsync `OUTPUT_URL` with `OUTPUT=PXE` now creates the `RSYNC_PREFIX` directory at the destination and the URL is interpreted as in all other cases. "

Does it make sense? I know it is complicated. Too many special cases, fortunately it is about removing some of them...

File: usr/share/rear/lib/rsync-functions.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh]: Indeed, the possibility that the user has supplied a non-rsync URL whern rsync is expected is handled in the caller, `prep/RSYNC/default/100_check_rsync.sh`:
```bash
local scheme=$(url_scheme $BACKUP_URL)  # url_scheme still recognizes old style

if [[ "$scheme" != "rsync" ]]; then
    Error "Missing BACKUP_URL=rsync://[USER@]HOST[:PORT][::]/PATH !"
fi
```

File: usr/share/rear/lib/rsync-functions.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:17]: Done in 2008a537ec5c152438488b849c72de4b2e36f141

**Comment by didacog** [comment]
Hello, seems that you are avoiding OUTPUT_PREFIX_PXE and is not being created when set in the config.

**Comment by jsmeix** [comment]
@didacog 
I will act for now here for @pcahyna
until he has again time to look here
but I am neither a PXE user nor a rsync user
so I can not at all imagine what you have
in your etc/rear/local.conf

Therefore please provide here sufficient information
that I have at least a chance to understand your issue
in particular your complete etc/rear/local.conf
and your complete etc/rear/site.conf if you use one.
I need the actual ReaR config files because
I am not a DRLM user so DRLM config files are "foreign" for me.
Additionally I need a complete ReaR debugscript log file
to have a chance to deduce what happens on your system.

Only FYI:
I want to release ReaR 2.7 on the date specified on
https://github.com/rear/rear/milestones
because I already postponed it rather often and
I can't wait endlessly until every issue is solved
because I am under increasing pressure to release
a new ReaR version (regardless if it is perfect or not).
For SUSE I could fix missing things relatively easy
by SUSE maintenance updates for our SLE-HA customers
and I assume it is same for Red Hat for RHEL customers.
Other users could use our latest master code.

**Comment by jsmeix** [comment]
Regarding OUTPUT_PREFIX_PXE I see no difference between
the changed code here and the master code:
```
localhost:~/rear.pcahyna.rsync-url-fix-refactor.pullrequest2831 # find usr/sbin/rear usr/share/rear -type f | xargs grep 'OUTPUT_PREFIX_PXE' >/tmp/OUTPUT_PREFIX_PXE.pcahyna.rsync-url-fix-refactor


localhost:~/rear.github.master # find usr/sbin/rear usr/share/rear -type f | xargs grep 'OUTPUT_PREFIX_PXE' >/tmp/OUTPUT_PREFIX_PXE.rear.github.master

# diff -s /tmp/OUTPUT_PREFIX_PXE.rear.github.master /tmp/OUTPUT_PREFIX_PXE.pcahyna.rsync-url-fix-refactor
Files /tmp/OUTPUT_PREFIX_PXE.rear.github.master and /tmp/OUTPUT_PREFIX_PXE.pcahyna.rsync-url-fix-refactor are identical
```
so it seems nothing was changed regarding OUTPUT_PREFIX_PXE here.

**Comment by pcahyna** [comment]
@jsmeix still here... I don't think that `OUTPUT_PREFIX_PXE` is the problem (it had no special handling in the old code indeed, so it should not need one now), but there is something else going on.

**Comment by jsmeix** [comment]
@pcahyna 
I appreciate it that you still participate here
but you don't need if you don't like and when you have
currently better things "to do" with "higher priority" ;-)

**Comment by jsmeix** [comment]
I have a plan how to proceed with this issue:

I would like to merge it tomorrow afternoon
unless there are objections from @pcahyna or @rear/contributors 

My reasoning:
In its current state it is another good step forward
towards cleaned up rsync code in ReaR.
And when it is merged it is simpler and easier to get tested
by all users who use our current GhitHub master code.

Remaining issues because of our rsync code cleanup in ReaR
can and will be fixed via separated pull requests.

**Comment by pcahyna** [comment]
@jsmeix yes, I agree, the problem is that the current code has special output URL handling for `BACKUP=RSYNC`, which is inconsistent, since output should be independent on backup. See

https://github.com/pcahyna/rear/blob/5cb10407d08e0d923219c9b013d420a4b632843f/usr/share/rear/output/default/950_copy_result_files.sh#L132

This pull request makes the code respect `OUTPUT_URL` if it is not identical to `BACKUP_URL`, but does not remove this special handling. Should it be removed entirely before 2.7 ? Would be good for consistency, but it would mean more chaŋes and more testing (and also behavior changes).

**Comment by pcahyna** [comment]
> the problem is (...)

note that this is not the problem reported by @didacog, it is a separate problem (and not a regression, it has been always there).

**Comment by jsmeix** [comment]
@pcahyna 
I would prefer to not add new bigger changes for ReaR 2.7
so we could finally release it "as is" - even when 'rsync'
is currently not yet well cleaned up - but we also have some
more areas where current things in ReaR are not yet clean
(e.g. OUTPUT=USB and ReaR recovery system bootloader setup)
but nevertheless the current state should be sufficiently OK
to be released.

**Comment by jsmeix** [comment]
By the way only as a side note FYI see my
https://github.com/rear/rear/pull/2577#issuecomment-789696867
and the subsequent comment there
which looks like an inconsistency to me.

I think there should not be two subtle different methods
in ReaR to do the backup via rsync and I still do not understand
the reason behind why there are two different implementations
in ReaR to do the backup via rsync - this all is too confusing.

**Comment by jsmeix** [comment]
Normally users would not have to adapt their workflows/configs multiple times
because when a user has a working disaster recovery procedure with ReaR,
then he should not update ReaR ("never change a working system").
In contrast when things do not work sufficiently with an older ReaR version,
then the user should try out if a newer ReaR version works better.
Cf. the section "Version upgrades with Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

So we can move forward little step by little step
together with users who test each little step
which is the only way we can move forward
with our manpower at ReaR upstream.

**Comment by pcahyna** [comment]
> By the way only as a side note FYI see my [#2577 (comment)](https://github.com/rear/rear/pull/2577#issuecomment-789696867) and the subsequent comment there which looks like an inconsistency to me.
> 
> I think there should not be two subtle different methods in ReaR to do the backup via rsync and I still do not understand the reason behind why there are two different implementations in ReaR to do the backup via rsync - this all is too confusing.

Indeed, that has been very confusing to me as well, but it is yet a different kind of confusion than the one here. (And I have thought that the `BACKUP=NETFS` and `BACKUP_PROG=rsync` does not use rsync over ssh, but local rsync to a mounted filesystem, which makes more sense: the rsync invocation reads
```
$BACKUP_PROG --verbose "${BACKUP_RSYNC_OPTIONS[@]}" --one-file-system --delete \
            --exclude-from=$TMP_DIR/backup-exclude.txt --delete-excluded \
            $(cat $TMP_DIR/backup-include.txt) "$backuparchive" >&2
```
and `$backuparchive` does not contain anything ssh-transport-related. )

**Comment by jsmeix** [comment]
@pcahyna 
for the fun of it:
It's a great relief to me to see that also you and @gdha 
seem to be confused what BACKUP=NETFS with BACKUP_PROG=rsync
versus BACKUP=RSYNC actually does so I feel less lonely
with my own confusion :-)

**Review by jsmeix — APPROVED** [review]
Looks good to me from plain looking at the code

**Comment by jsmeix** [comment]
@rear/contributors 
I would like to merge it in a few hours
(at about 15:00) unless there are objections

**Comment by didacog** [comment]
please see https://github.com/rear/rear/issues/2781#issuecomment-1177558312 before merging!!!

**Comment by jsmeix** [comment]
@didacog 
thank you for debugging and for your fix!

Of course I will wait now until @pcahyna had a look.

So I will not merge it this week.
Perhaps next week if all goes well.

**Comment by jsmeix** [comment]
@pcahyna 
THANK YOU SO MUCH!

I think I can feel the "URI/URL parsing hell" a bit ;-)
I was in there when I cleaned up the url_* functions :-)

**Comment by jsmeix** [comment]
According to
https://github.com/rear/rear/issues/2781#issuecomment-1180233302
the issue https://github.com/rear/rear/issues/2781
is fixed with the latest commit here
https://github.com/rear/rear/pull/2831/commits/e7556a13eb95f21b5fb749c089facaf8678f3cd4
so I would like to merge this pull request tomorrow afternoon
unless there are objections by @rear/contributors

File: usr/share/rear/lib/rsync-functions.sh [hunk 4]
```diff
@@ -74,25 +74,39 @@ function rsync_path () {
...
     local path
+    local url_without_scheme
+    local url_without_scheme_user
 
     host=$(url_host "$url")
     path=$(url_path "$url")
     local tmp2="${host#*@}"
 
+    url_without_scheme="${url#*//}"
+    url_without_scheme_user="${url_without_scheme#$(rsync_user "$url")@}"
```
Comment (jsmeix) [inline usr/share/rear/lib/rsync-functions.sh:85]: @pcahyna 
only a question out of curiosity:

For now all is OK i.e. no changes for ReaR 2.7
but I like to understand if something may have
to be done for ReaR 2.8 e.g. further cleanup.

I wonmder what the reason is why you cannot use
the url_username() function in lib/global-functions.sh
to get the user name?

Your rsync_user() function parses what url_host() results
but I made url_username() and url_password() functions which
should work generically for URIs/URLs which are of the form
```
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]
```

I guess for rsync URLs things are special so the generic
url_username() and url_password() functions don't work.

Or is there perhaps something wrong with the
current url_username() and url_password() functions
that should be enhanced of fixed for ReaR 2.8?

Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:85]: Short answer: I don't know, my code originated as a copy of the original rsync URL parsing stuff in 
https://github.com/rear/rear/blob/a865e33e12d55f3f92ec06eda0efb147c153076b/usr/share/rear/prep/RSYNC/default/100_check_rsync.sh . I though it is a good idea to only move code around and make it more generic without changing how it works, because it reduces the likelihood of regressions. It is well possible that the generic URL functions are well sufficient for this purpose. (Note though that not all URL functions are suitable for all cases in this file, because they don't cope well with URLs where the path is not separated by a slash from host, as it is the case with old-style rsync URLs, where `:` or `::` is used as the separator.) It would take more analysis and experimenting to determine whether `url_username()` falls in the "suitable" or in the "unsuitable" category, which can be done for 2.8 indeed. (Note: I am not at all sure that rsync URLs support an embedded password, especially if `:` is used as a separator between user and password, since `:` is already a bit overloaded - it separates host from path in old-style scp-like rsync-over-ssh URLs, and also host from port in rsync protocol URLs.)

Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:85]: I don't believe that the syntax `scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]` is entirely accurate. At least the `/` separating host and path does not seem to be optional for our `url_` functions.

Comment (jsmeix) [reply usr/share/rear/lib/rsync-functions.sh:85]: Via
https://github.com/rear/rear/commit/606cb40607b1a90b91e44c8744c49c3e53adb203
I fixed the comment in lib/global-functions.sh
that shows a generic URI/URL syntax so it shows now
```
scheme:[//[[user:password@]host[:port]]/path[?query][#fragment]
```

Comment (jsmeix) [reply usr/share/rear/lib/rsync-functions.sh:85]: Via
https://github.com/rear/rear/commit/bdc467363e5189cecd4a649de7947eb59b064fa3
I fixed the before falsely fixed comment
that shows now only a usual generic URI/URL syntax so it is now
```
scheme://[[user:password@]host[:port]]/path[?query][#fragment]
```
so the case `scheme:path` (like `mailto:John.Doe@example.com`)
is left out for simplicity in that comment because
I don't know if the current `url_...` functions
support the `scheme:path` case.

Comment (pcahyna) [reply usr/share/rear/lib/rsync-functions.sh:85]: They don't, actually. `url_scheme()` searches for `://`, not `:` (which makes sense, as `:` is used in old-style rsync "URLs" (that are not real URLs) as a separator). So your change is correct. `://` is much more visually clear anyway, so I would not even attempt to support `scheme:path`, unless there is a real need.

**Comment by pcahyna** [comment]
By the way, I tested the code after the last commit again by backing up/recovering to/from a `rsync://` BACKUP_URL (only rsync over ssh was tested though) and several possibilities for OUTPUT_URL. All the tests pass.

File: usr/share/rear/lib/rsync-functions.sh (hunk 4 above)
Comment (jsmeix) [reply usr/share/rear/lib/rsync-functions.sh:85]: Yes, that the old style rsync "URLs" are no URLs
(because `[USER@]HOST:[:]PATH` is invalid URI syntax)
is another good reason to clean that up properly
when there is real need for such a cleanup, cf.
https://github.com/rear/rear/issues/2781#issuecomment-1181617916
