### PR TITLE
Supply default value for root in grub in UEFI ISO

### LINKED ISSUE #2434: UEFI ISO won't boot with rear 2.6
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
`Relax-and-Recover 2.6 / 2020-06-17`

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
`Debian GNU/Linux 10 (buster)`

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```OUTPUT=ISO
OUTPUT_URL=file:///var/tmp
BACKUP=NETFS
BACKUP_URL=iso://backup
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/var/tmp' ........ )
ISO_MAX_SIZE=4400
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
`KVM VM`

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
`x86`

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
`UEFI (ovmf, tianocore on debian9 libvirt) + grub 2.0.2+dfsg1-20`

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
`local`

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):

* Description of the issue (ideally so that others can reproduce it):
With rear-2.5-0 we could create bootable UEFI ISOs. With rear-2.6-0 we get the error message
```
Loading kernel ...
error: file '/isolinux/kernel' not found.
Loading initial ramdisk
error: you need to load the kernel first.

It looks like the grub load doesn't search for the kernel on the loaded iso image. We downgraded to rear-2.5-0 and created the same 
```

* Workaround, if any:
```
edit the grub commands

before:
linux /isolinux/kernel ...
initrd /isolinux/initrd.cgz

after:
linux (cd0)/isolinux/kernel ...
initrd (cd0)/isolinux/initrd.cgz

F10 to boot
```

### PR DESCRIPTION
**Pull request by pcahyna**
##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **High**

* Reference to related issue (URL):

Fixes #2434. (problem introduced in PR #2293).

* How was this pull request tested?

Success was reported by @yontalcar in #2434 (for RHEL 7 and RHEL 8 only though).

* Brief description of the changes in this pull request:

Sometimes the search command in GRUB2 used in UEFI ISO does not find the root device. This was seen at least in Debian Buster running in Qemu (VirtualBox works fine, RHEL/CentOS in Qemu works fine as well).

To make ReaR work in this case, set $root to a sensible value before trying `search`. The GRUB2 image created by grub-mkstandalone has $root set to memdisk, which can't work.

This essentially matches how it used to work before PR #2293.

### CODE REVIEW

**Comment by jsmeix** [comment]
@gozora 
I dared to assign it to you because I spotted `UEFI` soewhere here ;-)
(of course I will also have a look)

File: usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh [hunk 1]
```diff
@@ -63,6 +63,7 @@ title Relax-and-Recover (no Secure Boot)
 EOF
 else
     # create a grub.cfg
+    grub2_set_root=cd0
```
Comment (jsmeix) [inline usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh:66]: @pcahyna 
please provide a comment that tells about the reason behind
why that `grub2_set_root=cd0` must be there,
cf. "Code must be easy to understand" in
https://github.com/rear/rear/wiki/Coding-Style

Comment (jsmeix) [reply usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh:73]: Done via
https://github.com/rear/rear/pull/2453/commits/77d04392f71a055ff31d1e4e52c4554110d38d48

**Comment by jsmeix** [comment]
https://github.com/rear/rear/pull/2453/commits/77d04392f71a055ff31d1e4e52c4554110d38d48
adds the missing comment, cf. https://github.com/rear/rear/pull/2453#discussion_r449644820

**Comment by jsmeix** [comment]
@gozora 
feel free to merge it if things look OK for you
(in particular when my comment describes things correctly).

**Comment by pcahyna** [comment]
@jsmeix thank you for adding the comment yourself and sorry for my late reaction.

**Comment by jsmeix** [comment]
@pcahyna 
My pleasure!
Thank you for the fix.

@gozora 
Thank you for your continuous help with UEFI issues in ReaR!
