### PR TITLE
Remove the lvmdevices file at the end of recovery

### LINKED ISSUE #2917: EL 9 after "rear recover" to different HW reboot hangs at "A Start Job is running for /dev/mapper/vg01-..."
Hello there,

I'm trying to do a test bare-metal-recovery of an HP DL360G9 with Oracle Linux 9.0 and LVM 2.03.16 installed. The  ReaR version is 2.7 ( tried 2.6 as well). All goes well during the 'mkbackup' phase with only a few settings in local.conf:

OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=null
BACKUP_URL=iso:///backup
ISO_DIR=/mnt/usb/rescue_system
USER_INPUT_BACKUP_URL_ISO_PROCEED_MKRESCUE=y
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/mnt')
ISO_FILE_SIZE_LIMIT=8589934592
USE_SERIAL_CONSOLE='no'

The generated iso file ist booting flawlessly on new and identicaly equipped  HP DL360G9 hardware to this point:
image
a clouple of 'red' follow-up errors are thrown and the recovery image gets stuck and won't boot up to a login-prompt. 

Is this a bug? I tried to install the image to different hardware as well but the behavíour is still the same. Both machines got a HP 'Smart Array P440ar Controller' and a configured RAID1 logical drive. I switched the target controller to 'HBA' mode prior to recovery but without visible effect.

Regards, HG

### LINKED ISSUE #3042: use_devicesfile in RHEL9
ReaR version ("/usr/sbin/rear -V"):
rear-2.6-17.el9.x86_64

If your ReaR version is not the current version, explain why you can't upgrade:

OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Red Hat Enterprise Linux release 9.2 (Plow)

ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
BACKUP=NETFS
BACKUP_URL=nfs://XXX.uniforce.eu/GPFS/var/rear
OUTPUT=ISO
ONLY_INCLUDE_VG=('rootvg')

Hardware vendor/product:

System architecture:
x86_64

Firmware:
BIOS, GRUB2

Storage :
Local Disk

Storage layout: Not able to get any log for the disk layout

Description of the issue:

As of RHEL9, use_devicesfile in LVM seems to be enabled by default. The devices file contains information on the allowed PVIDs.
As we may be restoring on a different PV, the devices file needs to be recreated prior to rebooting after the restore.

Possible fix

chroot /mnt/local /bin/bash -c "rm /etc/lvm/devices/system.devices && /usr/sbin/vgimportdevices -a"

### PR DESCRIPTION
**Pull request by pcahyna**
#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **High**

* Reference to related issue (URL):  closes #2917, closes #3042 

* How was this pull request tested?
Full backup and recovery on a KVM virtual machine (x86_64) with virtio disk (vda) and a PowerVM LPAR (ppc64le) withs SCSI disk (sda), both with RHEL 9 (where the LVM default is `use_devicesfile=1`).
Before backup and recovery:

```
# cat /etc/lvm/devices/system.devices
# LVM uses devices listed in this file.
# Created by LVM command lvmdevices pid 3645 at Thu Aug 24 11:52:38 2023
VERSION=1.1.4
IDTYPE=sys_serial IDNAME=00fac60100004c000000017bead7ca41.10 DEVNAME=/dev/sda3 PVID=3NFhwAW1RAQzJz8uOsZqkcqasKhlZt9b PART=3
# lvmdevices 
  Device /dev/sda3 IDTYPE=sys_serial IDNAME=00fac60100004c000000017bead7ca41.10 DEVNAME=/dev/sda3 PVID=3NFhwAW1RAQzJz8uOsZqkcqasKhlZt9b PART=3
```
After recovery:
```
# lvmdevices 
  Devices file does not exist.
# cat /etc/lvm/devices/system.devices.rearbak 
# LVM uses devices listed in this file.
# Created by LVM command lvmdevices pid 3645 at Thu Aug 24 11:52:38 2023
VERSION=1.1.4
IDTYPE=sys_serial IDNAME=00fac60100004c000000017bead7ca41.10 DEVNAME=/dev/sda3 PVID=3NFhwAW1RAQzJz8uOsZqkcqasKhlZt9b PART=3
```

* Brief description of the changes in this pull request:

The file `/etc/lvm/devices/system.devices` restricts LVM to disks with given (hardware) IDs (serial numbers, WWNs). See lvmdevices(8).

Unfortunately, when restoring to different disks than in the original system, it will mean that LVM is broken in the recovered system (it won't find any disks).  Therefore it is safer to remove the file to force the old behavior where LVM scans all disks. This used to be the LVM default (`use_devicesfile=0`).

I don't think one can delete the devices file and do /usr/sbin/vgimportdevices -a to reimport the VGs automatically at the end of recovery. The problem is, imagine you have several volume groups. One for the system (rootvg) and one for data (datavg), on different disks. Now you system is broken and you want to recover it, but the data are unaffected and you want them to survive the recovery procedure. For this, it is advisable to disconnect the data disks during the recovery procedure to avoid accidentally reformatting them. But, as they are not connected, /usr/sbin/vgimportdevices -a will not find datavg, therefore it will not add them to the devices file and when you reboot after recovery with the disks attached again, they will not be found by LVM and datavg will not be activated.
I was thinking about some automated procedure to update only the obsolete entries in lvmdevices and keep all others, but I have not found anything simple. I therefore believe the only reliable solution is to remove the devices file at the end of recovery, since running without it is preferable to a broken system due to some fragile attempt at an "ideal" solution.

### CODE REVIEW

**Comment by pcahyna** [comment]
@rear/contributors I would like to merge the PR quite soon, if there is nothing obviously wrong with it. I believe the approach is safe, even if not ideal (we are reverting to the old behavior without devices file) and after much thinking I have not found a better approach.

**Comment by pcahyna** [comment]
Relevant part of console output:
```
Created SELinux /mnt/local/.autorelabel file : after reboot SELinux will relabel all files 
Recreating directories (with permissions) from /var/lib/rear/recovery/directories_permissions_owner_group 
Checking if certain restored files are consistent with the recreated system 
Renamed LVM devices file /mnt/local//etc/lvm/devices/system.devices to /mnt/local//etc/lvm/devices/system.devices.rearbak to prevent 
LVM problems in the recovered system, verify that the file is correct 
after booting the recovered system and move it back, or regenerate it 
using vgimportdevices. 
Migrating disk-by-id mappings in certain restored files in /mnt/local to current disk-by-id mappings ... 
Running dracut... 
```

File: usr/share/rear/finalize/GNU/Linux/230_remove_lvmdevices.sh [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+# by default
+
+local file=/etc/lvm/devices/system.devices
+local realfile
+
+realfile="$TARGET_FS_ROOT/$file"
+# OK if file not found
+test -f "$realfile" || return 0
+mv $v "$realfile" "${realfile}.rearbak"
+LogPrint "Renamed LVM devices file $realfile to ${realfile}.rearbak
```
Comment (jsmeix) [inline usr/share/rear/finalize/GNU/Linux/230_remove_lvmdevices.sh:22]: I think the curly braces in `${realfile}.rearbak` are not needed
( cf. https://github.com/rear/rear/wiki/Coding-Style#variables )
because
```
# var=value

# echo $var.suffix
value.suffix
```
and "man bash" (with GNU bash version 4.4.23) reads:
```
DEFINITIONS
...
  name
    A word consisting only of alphanumeric characters and underscores,
    and beginning with an alphabetic character or an underscore.
    Also referred to as an identifier.

...

PARAMETERS
...
  A variable may be assigned to by a statement of the form
    name=[value]
```

**Review by jsmeix — APPROVED** [review]

File: usr/share/rear/finalize/GNU/Linux/230_remove_lvmdevices.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/finalize/GNU/Linux/230_remove_lvmdevices.sh]: done.
