### PR TITLE
Skip invalid disk drives (zero sized, no media) when saving layout

### LINKED ISSUE #2958: ReaR fails while verifying the disklayout when a disk has a 0 size
* ReaR version ("/usr/sbin/rear -V"):

latest upstream 2.7 at latest commit 7ce864210fc7a7c95a131ea8c933f543b6e3b9cb

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

N/A

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

~~~
AUTOEXCLUDE_DISKS=n
~~~

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):

N/A

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

N/A

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

N/A

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

USB Card Reader with no card inserted

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

N/A

* Description of the issue (ideally so that others can reproduce it):

When plugging in a USB multi-card reader (SD / MicroSD) which has no card insert, the device (`/dev/sda`) has a 0 size.
This leads to layout verification to fail:
~~~
No partition label type for 'disk /dev/sda' (may cause 'rear recover' failure)
/dev/sda size 0 is not a positive integer
ERROR: 
====================
BUG in /root/rear/usr/share/rear/layout/save/default/950_verify_disklayout_file.sh line 254:
'Entries in /root/rear/var/lib/rear/layout/disklayout.conf are broken ('rear recover' would fail)'
~~~

This happens when `AUTOEXCLUDE_DISKS=n` (which is not the default).

* Workaround, if any:

None found yet, except excluding the "disk" manually, which isn't always possible due to non-persistent device naming.

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

The root cause is the code snippet in `/usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh`, which doesn't skip disks with `$devsize == 0` :
~~~
415                 devsize=$(get_disk_size ${disk#/sys/block/})
416                 disktype=$(parted -s $devname print | grep -E "Partition Table|Disk label" | cut -d ":" -f "2" | t    r -d " ")
 :
430                     echo "disk $devname $devsize $disktype"
~~~

This leads to creating entry `disk sda 0`, which is invalid entry (missing `$disktype`).

I think the solution is to skip those 0 size disks completely.

### PR DESCRIPTION
**Pull request by pcahyna**
##### Pull Request Details:

* Type:  **Enhancement**

* Impact: **Normal**

* Reference to related issue (URL): fixes #2958

* How was this pull request tested?
  * `rear savelayout` on Fedora 36 with empty USB SD card reader
     I show the relevant log excerpt and the corresponding part of `disklayout.conf`, if any.
    * original code:
      ```
      No partition label type for 'disk /dev/sdb' (may cause 'rear recover' failure)
      ```
      ```
      # Disk /dev/sdb
      # Format: disk <devname> <size(bytes)> <partition label type>
      #disk /dev/sdb 0 
      ```
    * new code:
      ```
      Ignoring sdb: blockdev: cannot open /dev/sdb: No medium found
      ```
      No sdb in disklayout
    * new code without reverting 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545
      same result
    * original code only with 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545 reverted
      This reproduces https://github.com/rear/rear/issues/2810
      ```
      ERROR: Invalid 'disk /dev/sdb' entry (no partition table type for '/dev/sdb')
      Some latest log messages since the last called script 200_partition_layout.sh:
        2023-06-20 19:23:08.249840221 Saving disks and their partitions
      Some messages from /var/tmp/rear.ZC1Unp4TNvGyfNj/tmp/rear.savelayout.stdout_stderr since the last called script 200_partition_layout.sh:
        blockdev: cannot open /dev/sdb: No medium found
        Error: Error opening /dev/sdb: No medium found
      Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
      Aborting due to an error, check /home/pcahyna/rear/rear/var/log/rear/rear-pacaziste.log for details
      Terminated
      ```
  * `rear savelayout` on Fedora 36 with empty USB SD card reader and `AUTOEXCLUDE_DISKS=n`
    * original code:
      ```
      No partition label type for 'disk /dev/sdb' (may cause 'rear recover' failure)
      /dev/sdb size 0 is not a positive integer
      ERROR: 
      ====================
      BUG in /home/pcahyna/rear/rear/usr/share/rear/layout/save/default/950_verify_disklayout_file.sh line 257:
      'Entries in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are broken ('rear recover' would fail)'
      --------------------
      Please report it at https://github.com/rear/rear/issues
      and include all related parts from /home/pcahyna/rear/rear/var/log/rear/rear-pacaziste.log
      preferably the whole debug information via 'rear -D savelayout'
      ====================
      Some latest log messages since the last called script 950_verify_disklayout_file.sh:
        2023-06-20 19:16:28.417175129 Verifying that the entries in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are correct
        2023-06-20 19:16:28.424548585 Verifying that the 'disk' entries in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are correct
        2023-06-20 19:16:28.436529921 Verifying that the 'part' entries for /dev/sda in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are correct
        2023-06-20 19:16:28.446834398 Verifying that the 'part' entries for /dev/sda in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf specify consecutive partitions
        2023-06-20 19:16:28.458051434 Verifying that the 'part' entries for /dev/sdb in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are correct
        2023-06-20 19:16:28.468396791 Verifying that the 'part' entries for /dev/sdb in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf specify consecutive partitions
        2023-06-20 19:16:28.473731880 Verifying that the 'lvm...' entries in /home/pcahyna/rear/rear/var/lib/rear/layout/disklayout.conf are correct
        2023-06-20 19:16:28.506275876 /dev/sdb size 0 is not a positive integer
      Some messages from /var/tmp/rear.dSRYZZLoczSVake/tmp/rear.savelayout.stdout_stderr since the last called script 950_verify_disklayout_file.sh:
        256060514304
        1073741824
        1048576
        254985371648
        1074790400
        0
      Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
      Aborting due to an error, check /home/pcahyna/rear/rear/var/log/rear/rear-pacaziste.log for details
      Terminated
      ```
      ```
      # Disk /dev/sdb
      # Format: disk <devname> <size(bytes)> <partition label type>
      disk /dev/sdb 0 
      # Partitions on /dev/sdb
      ```
      This reproduces #2958
    * new code:
      ```
      Ignoring sdb: blockdev: cannot open /dev/sdb: No medium found
      ```
      No sdb in disklayout
    * new code without reverting 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545
      same result
  * full backup and recovery on RHEL 8 with empty USB SD card reader
     ```
     Running 'layout/save' stage ======================
     Creating disk layout
     Ignoring sde: blockdev: cannot open /dev/sde: No medium found
     Automatically excluding disk /dev/sdb (not used by any mounted filesystem)
     Marking component '/dev/sdb' as done in /var/lib/rear/layout/disktodo.conf
     Automatically excluding disk /dev/sdc (not used by any mounted filesystem)
     Marking component '/dev/sdc' as done in /var/lib/rear/layout/disktodo.conf
     Automatically excluding disk /dev/sdd (not used by any mounted filesystem)
     Marking component '/dev/sdd' as done in /var/lib/rear/layout/disktodo.conf
     Disabling excluded components in /var/lib/rear/layout/disklayout.conf
     Disabling component 'disk /dev/sdb' in /var/lib/rear/layout/disklayout.conf
     Disabling component 'disk /dev/sdc' in /var/lib/rear/layout/disklayout.conf
     Disabling component 'disk /dev/sdd' in /var/lib/rear/layout/disklayout.conf
     ```
  * full backup and recovery on RHEL 8 with empty USB SD card reader and `AUTOEXCLUDE_DISKS=n`
     ```
     Running 'layout/save' stage ======================
     Creating disk layout
     Ignoring sde: blockdev: cannot open /dev/sde: No medium found
     Disabling excluded components in /var/lib/rear/layout/disklayout.conf
     ```
* Brief description of the changes in this pull request:
    * Introduce function is_disk_valid, which performs checks for disk usability beyond validating the device name, and use it when saving the disk layout. In some cases the device name may be valid, but there are no data, typically because it is a drive with removable media and there is no medium in the tray. Happens typically with card (e.g. SD card) readers with empty slot.
       This is a normal occurrence, so do not Error out, only display a message and skip the device.
    * Revert commit 0a1d634ed15500bb21f37ac1bbb11c8a4bb11545 . We now skip disks with no data (like when there is no medium), so incomplete disk entries (without partition type) should not occur anymore. Restore the code that aborted when such disks were encountered.
       Incomplete entries should not be allowed to occur, as they could confuse the layout restoration code. Moreover, the layout restoration wipes all disks in the layout, so if during layout restoration there happens to be a medium in the drive that was empty during layout save, the data on the medium would get overwritten and lost. And if there is not medium, the layout recreation script would fail.
      See the discussion at https://github.com/rear/rear/issues/2958#issuecomment-1479588829

### CODE REVIEW

File: usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh [hunk 1]
```diff
@@ -413,17 +413,16 @@ Log "Saving disks and their partitions"
...
                 # Each value must exist and each value must be a single non-blank word so we 'test' without quoting the value:
                 test $devname || Error "Invalid 'disk' entry (no disk device name for '$disk')"
                 test $devsize || Error "Invalid 'disk $devname' entry (no device size for '$devname')"
-                # We do not error out when there is no partition label type value because
-                # "rear recover" works in a special case without partition label type value when there is
-                # only a 'disk' entry but nothing else for this disk exists in disklayout.conf
-                # which can happen when /dev/sdX is an empty SD card slot without medium,
-                # see https://github.com/rear/rear/issues/2810
-                test $disktype || LogPrintError "No partition label type for 'disk $devname' (may cause 'rear recover' failure)"
+                if ! validation_error=$(is_disk_valid $devname) ; then
```
Comment (jsmeix) [inline usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh:420]: Please add a comment here that points to
https://github.com/rear/rear/pull/3047
because that has an explanatory description
of the whole reasoning behind, i.e. why we test
this way and why we do not error out here.

File: usr/share/rear/lib/layout-functions.sh [hunk 2]
```diff
@@ -819,6 +819,40 @@ is_disk_a_pv() {
...
+# Check whether disk is suitable for being added to layout
+# Can be used to skip obviously unsuitable/broken devices
+# (missing device node, zero size, device can't be opened).
+# Should not be used to skip potential mapping targets before layout restoration
+# - an invalid disk may become valid later, for example if it is a DASD that needs
+# low-level formatting (see 090_include_dasd_code.sh and 360_generate_dasd_format_code.sh),
+# unformatted DASDs show zero size.
+# Returns 0 if the device is ok
+# Returns nonzero code if it should be skipped, and a text describing the error
+# (without the device name) on stdout
```
Comment (jsmeix) [inline usr/share/rear/lib/layout-functions.sh:831]: I think the error messages contain the device name
```
echo "$disk is not a block device"
echo "$disk has invalid size $size"
```
Only the `blockdev --getsize64` output
may not contain the device in some cases
but it seems usually the `blockdev --getsize64` output
does contain the device like in your
https://github.com/rear/rear/pull/3047#issue-1890627700
```
Ignoring sdb: blockdev: cannot open /dev/sdb: No medium found
```
or on my system
```
# blockdev --getsize64 /dev/sdb
blockdev: cannot open /dev/sdb: No such file or directory

# blockdev --getsize64 /dev/sda12
blockdev: cannot open /dev/sda12: No such file or directory
```

**Review by jsmeix — APPROVED** [review]

**Comment by jsmeix** [comment]
@pcahyna 
thank you for this enhancement and
the cleanup of the old clumsy code
and for your explanatory description
of the various cases (in particular
things like the special DASD case)!

File: usr/share/rear/lib/layout-functions.sh (hunk 2 above)
Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:831]: Yes, the message is perfectly well.

All I liked to point out is that the
"(without the device name)" part of the comment
is probably not true.

File: usr/share/rear/lib/layout-functions.sh [hunk 3]
```diff
@@ -819,6 +819,40 @@ is_disk_a_pv() {
...
+        echo "$disk is not a block device"
+        return 1
+    fi
+    # capture stdout in a variable and redirect stderr to stdout - the error message
+    # will be our output
+    if { size=$(blockdev --getsize64 "$disk") ; } 2>&1 ; then
+        if ! test "$size" -gt 0 2>/dev/null ; then
+            echo "$disk has invalid size $size"
+            return 1
+        fi
```
Comment (jsmeix) [inline usr/share/rear/lib/layout-functions.sh:850]: For easier understanding of the logic
I am wondering if an explicit 'returm 0' here
would be good?
At least to me it looked as if is_disk_valid()
would always 'return 1'.

Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:850]: Or with "Return early, return often" style, cf.
https://github.com/rear/rear/wiki/Coding-Style#return-early-return-often
perhaps even like:
```
    if { size=$( blockdev --getsize64 "$disk" ) ; } 2>&1 ; then
        test "$size" -gt 0 2>/dev/null && return 0
        echo "$disk has invalid size $size"
        return 1
    fi
    return 1
```

Comment (pcahyna) [reply usr/share/rear/lib/layout-functions.sh:850]: > Or with "Return early, return often" style, cf. https://github.com/rear/rear/wiki/Coding-Style#return-early-return-often perhaps even like:
> 
> ```
>     if { size=$( blockdev --getsize64 "$disk" ) ; } 2>&1 ; then
>         test "$size" -gt 0 2>/dev/null && return 0
>         echo "$disk has invalid size $size"
>         return 1
>     fi
>     return 1
> ```

This also looks like the function always returns 1 - `return 0` at the end of a complex line of code is easy to miss.

File: usr/share/rear/lib/layout-functions.sh (hunk 2 above)
Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:831]: For the fun of it:
I found a blockdev error message that does not show the device:
```
# blockdev --getsize64 /dev/ttyS9
blockdev: ioctl error on BLKGETSIZE64: Input/output error
```
So a message might look like
```
Ignoring sdz: blockdev: ioctl error on BLKGETSIZE64: Input/output error
```
which is still sufficiently well.

File: usr/share/rear/lib/layout-functions.sh (hunk 3 above)
Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:850]: A side note:
I wished I could do "post-if" like
```
return 0 if test "$size" -gt 0 2>/dev/null
```
instead of
```
test "$size" -gt 0 2>/dev/null && return 0
```

File: usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh:425]: @jsmeix done, please have a look

**Comment by pcahyna** [comment]
@jsmeix I believe I addressed all review comments in last 3 commits.

**Review by jsmeix — APPROVED** [review]

**Comment by jsmeix** [comment]
@pcahyna 
thank you for the fine tuning.
All looks perfect to me.
Feel free to merge it as you like.

File: usr/share/rear/lib/layout-functions.sh [hunk 4]
```diff
@@ -819,6 +819,41 @@ is_disk_a_pv() {
...
+    local disk="$1"
+    local size
+
+    if ! test -b "$disk" ; then
+        echo "$disk is not a block device"
+        return 1
+    fi
+    # capture stdout in a variable and redirect stderr to stdout - the error message
+    # will be our output
+    if { size=$(blockdev --getsize64 "$disk") ; } 2>&1 ; then
```
Comment (pcahyna) [inline usr/share/rear/lib/layout-functions.sh:846]: That stderr redirection was a bad idea - when using -D, the debug output caused by `set -x` gets on stdout and leaks into the `validation_error` variable. A log excerpt when this happens:
```
++ validation_error='++++ blockdev --getsize64 /dev/nvme4n1
+++ size=171798691840'
```

Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:846]: I think stderr redirection is OK
but it was wrong implemented here because
```
{ COMMAND ; } 2>&1
```
redirects stderr before COMMAND is called
so it also redirects in particular 'set -x' output.

What is needed is to redirect stderr only for COMMAND
like in this example
```
# ( set -x ; grep_stdout="$( grep 'foo' /does/not/exist 2>&1 )" ; echo "grep_stdout='$grep_stdout'" )
++ grep --color=auto foo /does/not/exist
+ grep_stdout='grep: /does/not/exist: No such file or directory'
+ echo 'grep_stdout='\''grep: /does/not/exist: No such file or directory'\'''
grep_stdout='grep: /does/not/exist: No such file or directory'
```

So I think correct redirection should be like
```
if size="$( blockdev --getsize64 "$disk" 2>&1 )" ; then
```

Comment (jsmeix) [reply usr/share/rear/lib/layout-functions.sh:846]: @pcahyna 

my offhanded
https://github.com/rear/rear/pull/3503
intends to fix the is_disk_valid() function
as far as I understand things from plain looking at the code.

I did not yet test anything because offhandedly I don't know
how to simluate a disk which is not OK in a test VM
which I can set up via 'virt-manager'.
