### PR TITLE
Fix #2419: RAWDISK output fails to boot with Grub 2 on UEFI

### LINKED ISSUE #2419: RAWDISK output fails to boot on Ubuntu >=18.04.4 using Grub 2 + UEFI without Secure Boot
* ReaR version: Relax-and-Recover 2.6 / Git
* OS version: Ubuntu 18.04.4 LTS, Ubuntu 20.04 LTS
* System architecture: x86_64
* Firmware and bootloader: UEFI, Grub 2 without Secure Boot
* Description of the issue:

If Grub 2 is used to boot a UEFI rescue medium created on Ubuntu 18.04 or 20.04 with RAWDISK output, which was **not** configured for Secure Boot, the following messages appear:
```text
error: file `/EFI/BOOT/x86_64/linuxefi.mod´ not found.
error: you need to load the kernel first.
```

This appears to be a regression, possibly caused by a change in Ubuntu's Grub packaging: According to this [mailing list post](https://lists.gnu.org/archive/html/help-grub/2016-08/msg00014.html), `linuxefi.mod` is a distribution-specific module.

NOTES:

* UEFI secure boot (also done via Grub 2) is not affected.
* UEFI booting via syslinux (another RAWDISK output option) is also not affected.

PR upcoming.

### PR DESCRIPTION
**Pull request by OliverO2**
##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): #2419

* How was this pull request tested? On Ubuntu 18.04.4 LTS and 20.04 LTS

* Brief description of the changes in this pull request:
    * RAWDISK output: Add distribution-specific module 'linuxefi.mod' to Grub

### CODE REVIEW

File: usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh [hunk 1]
```diff
@@ -19,7 +19,15 @@ fi
...
-[[ -d /usr/lib/grub/x86_64-efi ]] || [[ -d /usr/lib/grub2/x86_64-efi ]] || [[ -d /usr/share/grub2/x86_64-efi ]] || return 0
+local efi_modules_directory
+local dir
+for dir in /usr/lib/grub/x86_64-efi /usr/lib/grub2/x86_64-efi /usr/share/grub2/x86_64-efi; do
+    if [[ -d "$dir" ]]; then
+        efi_modules_directory="$dir"
+        break
+    fi
+done
+[[ -z "$efi_modules_directory" ]] && return 0
```
Comment (jsmeix) [inline usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh:31]: Only FYI if you like to simplify the code in the following way:
I think you could omit the helper variable `dir` because you coud do
```
# Use first found GRUB2 UEFI modules directory or skip the script if none exists:
local efi_modules_directory
for efi_modules_directory in /usr/lib/grub/x86_64-efi /usr/lib/grub2/x86_64-efi /usr/share/grub2/x86_64-efi ; do
    test -d "$efi_modules_directory && break
done
test -d "$efi_modules_directory" || return 0
```

**Comment by jsmeix** [comment]
@rear/contributors 
because this change affects only `OUTPUT=RAWDISK`
and because it was tested by @OliverO2 
I would like to merge it tomorrow morning
if there are no objections.

**Comment by gozora** [comment]
@OliverO2 
In general this PR looks OK to me.

Only for the future, it might be good idea to unite Grub2 UEFI code also for `OUTPUT=RAWDISK` . With https://github.com/rear/rear/commit/c67e24d32c09a86ca98733c2f2399f428e6ce071 @pcahyna introduced code for this purpose. Maybe it would be worth a wile to check if it would be usable also for `OUTPUT=RAWDISK`. Some example code can be found in [250_populate_efibootimg.sh](https://github.com/rear/rear/blob/03b36df5efc990c2dbccf3b37f9e3ba97c247c35/usr/share/rear/output/ISO/Linux-i386/250_populate_efibootimg.sh#L75).

V.

File: usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh (hunk 1 above)
Comment (OliverO2) [reply usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh:31]: Yes surely that would work, too. In this case I'd like to stick with `dir` because it's a bit more explicit and thus I think it's easier to grasp. Your's is shorter but looks a bit more tricky to me.

**Comment by pcahyna** [comment]
@gozora I would like to unify the code with my previous GRUB changes, but I don't have time for it now - @yontalcar do you want to have a look?

**Comment by OliverO2** [comment]
@gozora Actually, I've tried to use `build_bootx86_efi` in my attempt to fix this. Unfortunately, I was unable to make it work right away.

**Comment by OliverO2** [comment]
@pcahyna @yontalcar Some ideas from my side if `build_bootx86_efi` were to be used universally.

`RAWDISK` output is not just used to create a recovery image. It is also used to create a pre-boot-authentication system to unlock self-encrypting disks. Such a system must be pretty small (less than 128 MB) and boot quickly, silently and nicely (with a plymouth graphical splash if available). So in this case a minimal set of grub modules is required, the only file system support needed is GPT/FAT, but relevant video modes must be usable.

Using `build_bootx86_efi` would replace just one line in `usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh`:
```
    $grub2_name-mkimage -O x86_64-efi -o "$boot_loader" -p "/EFI/BOOT" "${grub_modules[@]}"
```

Would that be worth it? If you think so, could you consider including some documentation in `build_bootx86_efi` making some guarantees about its invocation (parameters, global variables, behavior) so that it is easier to use and things don't change unexpectedly later on?

File: usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh (hunk 1 above)
Comment (jsmeix) [reply usr/share/rear/output/RAWDISK/Linux-i386/270_create_grub2_efi_bootloader.sh:31]: @OliverO2 
I fully agree with you.

Cf. https://github.com/rear/rear/wiki/Coding-Style (excerpts):
```
Introduce intermediate variables with meaningful names
to tell what is going on.
...
Better very simple code than oversophisticated
(possibly fragile) constructs. 
```

By the way and only for the fun of it:
I found an even more "elegant" (a.k.a. "tricky") way to do all inside the `for` loop:
```
# Use first found GRUB2 UEFI modules directory or skip the script if none was found:
local efi_modules_directory
for efi_modules_directory in /usr/lib/grub/x86_64-efi /usr/lib/grub2/x86_64-efi /usr/share/grub2/x86_64-efi not_found ; do
    test -d "$efi_modules_directory" && break
    test 'not_found' = "$efi_modules_directory" && return 0
done
```
