### PR TITLE
Fix including of multipath disks in backup

### LINKED ISSUE #2236: Multipath disk incorrectly excluded from backup
* ReaR version ("/usr/sbin/rear -V"):

      # ./usr/sbin/rear -V
      Relax-and-Recover 2.5 / Git

  Git revision a252ca20b5dc9f34f6c8fffb61e055141ca37669 (current HEAD).

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

      # cat etc/rear/os.conf 
      OS_VENDOR=SUSE_LINUX
      OS_VERSION=12.2

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

      ```
      # cat etc/rear/local.conf
      BACKUP=NETFS
      BACKUP_OPTIONS="nfsvers=4,nolock"
      BACKUP_URL=nfs://192.168.122.1/srv/nfs/multipath-test
      REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" snapper chattr lsattr )
      COPY_AS_IS=( "${COPY_AS_IS[@]}" /usr/lib/snapper/installation-helper /etc/snapper/config-templates/default )
      BACKUP_PROG_INCLUDE=( /var/cache /var/lib/mailman /var/tmp /var/lib/pgsql /usr/local /opt /var/lib/libvirt/images /boot/grub2/i386-pc /var/opt /srv /boot/grub2/x86_64-efi /var/lib/mariadb /var/spool /var/lib/mysql /tmp /home /var/log /var/lib/named /var/lib/machines )
      AUTOEXCLUDE_DISKS=y
      AUTOEXCLUDE_MULTIPATH=n

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

  KVM guest.

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

  x86-64.

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

  UEFI + GRUB.

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

  Local disk + DM multipath.

* Description of the issue (ideally so that others can reproduce it):

  When using `AUTOEXCLUDE_MULTIPATH=n` `AUTOEXCLUDE_DISKS=y`, it is possible that a used multipath device is excluded from backup.

  Problematic configuration:
  * Disk `/dev/vda` holds root partition `/dev/vda2`.
  * Multipath device `/dev/mapper/0QEMU_QEMU_HARDDISK_0001` is backed by `/dev/sda`+`/dev/sdb` as slaves and contains partition `0QEMU_QEMU_HARDDISK_0001-part1` mounted at `/mnt/mp-1`.

  In the `disklayout.conf` speak:

      disk /dev/vda 17179869184 msdos
      part /dev/vda 1561329664 1048576 primary none /dev/vda1
      part /dev/vda 15617490944 1562378240 primary boot /dev/vda2
      fs /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1 /mnt/mp-1 ext4 uuid=8cf05242-2bd4-404b-b508-5235fd95e7a8 label= blocksize=1024 reserved_blocks=5% max_mounts=-1 check_interval=0d bytes_per_inode=4096 default_mount_options=user_xattr,acl options=rw,relatime,data=ordered
      fs /dev/vda2 / btrfs uuid=0b200db7-aa8f-4dcb-a8f5-843896599a38 label= options=rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot
      multipath /dev/mapper/0QEMU_QEMU_HARDDISK_0001 2147483648 /dev/sda,/dev/sdb
      part /dev/mapper/0QEMU_QEMU_HARDDISK_0001 209715200 1048576 primary none /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1

  In `diskdeps.conf`:

      /dev/vda1 /dev/vda
      /dev/vda2 /dev/vda
      fs:/mnt/mp-1 /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1
      fs:/mnt/mp-1 fs:/
      fs:/ /dev/vda2
      /dev/mapper/0QEMU_QEMU_HARDDISK_0001 /dev/sda
      /dev/mapper/0QEMU_QEMU_HARDDISK_0001 /dev/sdb
      /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1 /dev/mapper/0QEMU_QEMU_HARDDISK_0001

  With `AUTOEXCLUDE_DISKS=y`, ReaR excludes `fs:/mnt/mp-1`, `/dev/mapper/0QEMU_QEMU_HARDDISK_0001` and `/dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1` from the backup. The following seems to happen:

  * Code `320_autoexclude.sh` that handles automatic exclusion of disks starts processing `fs:/mnt/mp-1`. It calls `find_disk_and_multipath()` -> `find_disk()` -> `get_parent_components()`.

  * Function `get_parent_components()` calculates all parent elements for `fs:/mnt/mp-1`. The result is:

        /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1 fs:/ /dev/mapper/0QEMU_QEMU_HARDDISK_0001 /dev/vda2 /dev/sda /dev/sdb /dev/vda

  * Function `get_parent_components()` scans the ancestors for a correct type. The input type comes from `find_disk()` and is "disk". This results in `get_parent_components()` printing "/dev/vda" as its output.

  * Function `find_disk_and_multipath()` sees that `find_disk()` had a non-zero length output and propagates this result to its caller.

  * Code in `320_autoexclude.sh` records that `/dev/vda` is a used disk.

  The problem is that `find_disk_and_multipath()` never returns that `/dev/mapper/0QEMU_QEMU_HARDDISK_0001` is needed for `fs:/mnt/mp-1`, which results in excluding this disk and subsequently also excluding `fs:/mnt/mp-1`.

* Workaround, if any:

  The problem can be avoided by using `AUTOEXCLUDE_DISKS=n`.

### PR DESCRIPTION
**Pull request by petrpavlu**
#### Pull Request Details:

* Type: **Bug Fix** / **New Feature** / **Enhancement** / **Other?**

  **Bug Fix**.

* Impact: **Low** / **Normal** / **High** / **Critical** / **Urgent**

  **Normal**.

* Reference to related issue (URL):

  https://github.com/rear/rear/issues/2236.

* How was this pull request tested?

  Locally tested under KVM. Multipath configuration:

      # multipath -ll
      0QEMU_QEMU_HARDDISK_0001 dm-0 QEMU,QEMU HARDDISK
      size=2.0G features='1 retain_attached_hw_handler' hwhandler='0' wp=rw
      |-+- policy='service-time 0' prio=1 status=active
      | `- 2:0:0:1 sdb 8:16 active ready running
      `-+- policy='service-time 0' prio=1 status=enabled
        `- 2:0:0:2 sda 8:0  active ready running
      
      # parted /dev/mapper/0QEMU_QEMU_HARDDISK_0001 print
      Model: Linux device-mapper (multipath) (dm)
      Disk /dev/mapper/0QEMU_QEMU_HARDDISK_0001: 2147MB
      Sector size (logical/physical): 512B/512B
      Partition Table: gpt
      Disk Flags: 
      
      Number  Start   End     Size    File system  Name     Flags
       1      1049kB  211MB   210MB   ext4         primary
       2      211MB   2147MB  1937MB  xfs          primary
      
      # mount | grep 'on \(/ \|/mnt\)'
      /dev/vda2 on / type btrfs (rw,relatime,space_cache,subvolid=259,subvol=/@/.snapshots/1/snapshot)
      /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part1 on /mnt/mp-1 type ext4 (rw,relatime,data=ordered)
      /dev/mapper/0QEMU_QEMU_HARDDISK_0001-part2 on /mnt/mp-2 type xfs (rw,relatime,attr2,inode64,noquota)

* Brief description of the changes in this pull request:

  The `AUTOEXCLUDE_DISKS` logic (`320_autoexclude.sh`) traverses filesystems and tries to determine the associated underlying disks that should be kept. When having a filesystem `fs:/A` that is present on a multipath device `MP` and the root filesystem `fs:/` that is present on a normal disk `D`, the code first established that `fs:/A` depends on `fs:/` resulting in marking `D` as used and then short-circuited processing of multipath devices. This resulted in `MP` not being considered as a used device and removed from the backup.

  The patch fixes this problem by removing the short-circuit logic in `find_disk_and_multipath()` so multipath devices get processed too (unless `AUTOEXCLUDE_MULTIPATH` is true).

  Fixes #2236.

### CODE REVIEW

File: usr/share/rear/lib/layout-functions.sh [hunk 1]
```diff
@@ -318,10 +318,8 @@ find_disk() {
 }
 
 find_disk_and_multipath() {
-    res=$(find_disk "$1")
-    if [[ -n "$res" || "$AUTOEXCLUDE_MULTIPATH" =~ ^[yY1] ]]; then
-        echo $res
-    else
+    find_disk "$1"
+    if ! [[ "$AUTOEXCLUDE_MULTIPATH" =~ ^[yY1] ]]; then
```
Comment (jsmeix) [inline usr/share/rear/lib/layout-functions.sh]: Optionally when you are at it:

Things like `[[ "$VAR" =~ ^[yY1] ]]` is old code
See https://github.com/rear/rear/wiki/Coding-Style
for our current coding style recommendations.


Since a longer time we have the `is_true` and `is_false` functions
see usr/share/rear/lib/global-functions.sh
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/lib/global-functions.sh
how to use them.

**Comment by jsmeix** [comment]
@schabrolles @gdha 
could you have a look here and reviev it?

I cannot actually review it because I do not at all know about
how AUTOEXCLUDE_DISKS versus AUTOEXCLUDE_MULTIPATH
interdependencies are meant to work - i.e. I cannot imagine
if this chages may cause unexpected regressions elsewhere.

File: usr/share/rear/lib/layout-functions.sh (hunk 1 above)
Comment (setupji) [reply usr/share/rear/lib/layout-functions.sh]: Thanks, fixed in the updated patch.

**Comment by jsmeix** [comment]
@schabrolles 
if you do not object, I would like to merge it tomorrow.
