### PR TITLE
check for wrong array assignment in user configs

### LINKED ISSUE #2930: Ensure config array variables are specified as arrays by the user
It can lead to various rather unexpected behaviour
when an array variable is not set as an array
but usually as a string instead.

For example:
In bash assinging a string to an array
assingns the first array element to that string:
```
#  arr=()

# declare -p arr
declare -a arr=()

# arr=''

# declare -p arr
declare -a arr=([0]="")
```
But an array with an empty first element is something different
than an empty array which can make big differences in how
things behave, see for example
https://github.com/rear/rear/issues/2911
therein in particular
https://github.com/rear/rear/issues/2911#issuecomment-1387056556
and subsequent comments.

From the bash manpage section "Arrays":
```
Referencing an array variable without a subscript
is equivalent to referencing the array with a subscript of 0
```

To avoid that users set config array variables
as something that is not an array we should check
after sourcing the config files that the array variables
that are set in default.conf are still arrays.

See
https://github.com/rear/rear/issues/2925#issuecomment-1429432172

### PR DESCRIPTION
**Pull request by schlomo**
fixes #2930 

I wrote something that has this effect:

```
rear-sle15sp4:/src/rear # cat /etc/rear/local.conf 
BACKUP_PROG_INCLUDE=( $(findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash') )
COPY_AS_IS=foobar
rear-sle15sp4:/src/rear # rear help
ERROR: Missing array assignment like +=(...) for COPY_AS_IS in /etc/rear/local.conf:
COPY_AS_IS=foobar

Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
Aborting due to an error, check /var/log/rear/rear-rear-sle15sp4.log.lockless for details
Terminated
```

What do you think?

### CODE REVIEW

**Comment by schlomo** [comment]
@rear/contributors what do you think? As usual, no comment means I will merge tomorrow.

File: usr/share/rear/init/default/001_verify_config_arrays.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
+# ensure that all array variables defined in default.conf are still array variables after
+# reading the user configuration, fixes common user config error: https://github.com/rear/rear/issues/2930
+
+array_variables=($(
```
Comment (jsmeix) [inline usr/share/rear/init/default/001_verify_config_arrays.sh:4]: use 'local' for local variables,
see "Variables" in
https://github.com/rear/rear/wiki/Coding-Style

Comment (schlomo) [reply usr/share/rear/init/default/001_verify_config_arrays.sh:4]: I thought about that but `local` is supposed to work only in functions and this is not in a function...??

File: usr/share/rear/init/default/001_verify_config_arrays.sh [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+
+for config in "$CONFIG_DIR"/{site,local,rescue}.conf "${CONFIG_APPEND_FILES_PATHS[@]}"; do
+    test -r "$config" || continue
+    for var in "${array_variables[@]}"; do
+        mapfile -t var_assignments < <(
+            sed -n -E -e "/$var\+?=/p" "$config"
+            )
+        for line in "${var_assignments[@]}"; do
+            [[ "$line" == *$var?(+)=\(* ]] || Error "Missing array assignment like +=(...) for $var in $config:$LF$line$LF"
```
Comment (jsmeix) [inline usr/share/rear/init/default/001_verify_config_arrays.sh:16]: Better only tell what the actual error is
and avoid to teach the user what he should do.
So
```
... || Error "$var not assigned as array in $config: '$line'"
```
is simpler and more to the point.

File: usr/share/rear/init/default/001_verify_config_arrays.sh [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+        done
+    done
+done
+
+
+unset array_variables
```
Comment (jsmeix) [inline usr/share/rear/init/default/001_verify_config_arrays.sh:22]: This is obsolete when you use 'local' for local variables.

File: usr/share/rear/init/default/001_verify_config_arrays.sh (hunk 1 above)
Comment (jsmeix) [reply usr/share/rear/init/default/001_verify_config_arrays.sh:4]: See the section "Variables" in
https://github.com/rear/rear/wiki/Coding-Style
```
All scripts in usr/share/rear/ are
sourced from within the Source() function
so you can and should use 'local'
for local variables in scripts.
```
At least this is my understanding how it works
(but too often my understanding is incomplete
 and what actualy happens is a bit different).

Comment (schlomo) [reply usr/share/rear/init/default/001_verify_config_arrays.sh:4]: Ahhh, good point and excellent thinking! Thank you!

File: usr/share/rear/init/default/001_verify_config_arrays.sh (hunk 3 above)
Comment (schlomo) [reply usr/share/rear/init/default/001_verify_config_arrays.sh]: :heavy_check_mark:

File: usr/share/rear/init/default/001_verify_config_arrays.sh (hunk 2 above)
Comment (schlomo) [reply usr/share/rear/init/default/001_verify_config_arrays.sh]: :heavy_check_mark:

**Comment by schlomo** [comment]
Now it looks like this:
```
# usr/sbin/rear -C /tmp/bad help
ERROR: Syntax error: Variable BACKUP_PROG_INCLUDE not assigned as Bash array in /tmp/bad.conf:
BACKUP_PROG_INCLUDE="( $(findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash') )"

Use debug mode '-d' for some debug messages or debugscript mode '-D' for full debug messages with 'set -x' output
Aborting due to an error, check /src/rear/var/log/rear/rear-rear-sle15sp4.log.lockless for details
Terminated
```

**Comment by schlomo** [comment]
And now we catch even these cases:
* variables that contain other variable names
* multiple assignment on the same line

```
# cat /tmp/bad.conf 
F_BACKUP_PROG_INCLUDE="( $(findmnt -n -r -o TARGET -t btrfs | grep -v '^/$' | egrep -v 'snapshots|crash') )"
COPY_AS_IS=() BACKUP_PROG_INCLUDE=foobar

# usr/sbin/rear -D -C /tmp/bad help
Sourcing additional configuration file '/tmp/bad.conf'
Running 'init' stage ======================
ERROR: Syntax error: Variable BACKUP_PROG_INCLUDE not assigned as Bash array in /tmp/bad.conf:
COPY_AS_IS=() BACKUP_PROG_INCLUDE=foobar

```

**Comment by jsmeix** [comment]
It was merged too fast
because `mapfile` is not availabe in older bash,
at least not in GNU bash version 3.1.17 on SLES10
(SLE10 is the oldest one I have and I use that
 to check what there is on rather old systems):
```
# type -a mapfile
-bash: type: mapfile: not found

# bash --version
GNU bash, version 3.1.17 ...
```

`mapfile` is a bash 4.x thing according to
https://tldp.org/LDP/abs/html/bashver4.html
```
The new mapfile builtin ...
```

I suggest to add at the beginning of
init/default/001_verify_config_arrays.sh
a simple fail safe check like
```
# Skip this test when 'mapfile' (a bash 4.x builtin) is not available:
type -a mapfile 1>/dev/null || return 0
```
because that script is optional.

That '1>/dev/null' is only there to suppress needless
```
mapfile is a shell builtin
```
output which would appear in the log file in debug modes
but on the other hand it does not hurt in the log file in debug modes
so perhaps the simpler the better without needless '1>/dev/null'.

**Comment by schlomo** [comment]
Ah, good catch. I was wondering about that and will change it back to use our good old `( $() )` syntax as IMHO there is no real benefit to using `mapfile`.

Thanks!
