### PR TITLE
Cleanup rsync and fix error reporting

### LINKED ISSUE #2612: 400_restore_rsync_backup.sh does not show an error when restore rsync archive failed
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="diskimage_${HOSTNAME}"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://diskimage@xxxx::rsync_backup
BACKUP_URL=rsync://diskimage@xxxx::rsync_backup
BACKUP_RSYNC_OPTIONS+=(-z --progress )
ISO_DIR="/var/www/html/imageBackup/iso/$HOSTNAME"
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
export TMPDIR="/var/www/html/imageBackup/iso/"
PXE_RECOVER_MODE=automatic
ISO_FILES=("/var/www/html/imageBackup/rsync")
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Virtual machine

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI and GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
```
NAME              MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
sda                 8:0    0   20G  0 disk
├─sda1              8:1    0  977M  0 part
│ └─md127           9:127  0  976M  0 raid1 /boot
├─sda2              8:2    0  601M  0 part
│ └─md125           9:125  0  601M  0 raid1 /boot/efi
└─sda3              8:3    0 17.3G  0 part
  └─md126           9:126  0 17.3G  0 raid1
    ├─centos-root 253:0    0 13.5G  0 lvm   /
    └─centos-swap 253:1    0  3.8G  0 lvm   [SWAP]
sdb                 8:16   0   20G  0 disk
├─sdb1              8:17   0  977M  0 part
│ └─md127           9:127  0  976M  0 raid1 /boot
├─sdb2              8:18   0  601M  0 part
│ └─md125           9:125  0  601M  0 raid1 /boot/efi
└─sdb3              8:19   0 17.3G  0 part
  └─md126           9:126  0 17.3G  0 raid1
    ├─centos-root 253:0    0 13.5G  0 lvm   /
    └─centos-swap 253:1    0  3.8G  0 lvm   [SWAP]
sr0                11:0    1 1024M  0 rom
```

* Description of the issue (ideally so that others can reproduce it):
Unable to perform the recovery option.
Getting error like "Failed to create UFI Boot Manager entries".
Note: Downloaded the package today only.

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[rear-localhost.log](https://github.com/rear/rear/files/6432513/rear-localhost.log)

### PR DESCRIPTION
**Pull request by pcahyna**
##### Pull Request Details:

* Type: **Bug Fix** / **Cleanup**

* Impact: **High**

* Reference to related issue (URL): #2612, #2577

* How was this pull request tested?
Against CentOS 7:
  1. full backup and restore using rsync over ssh
  2. added nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )`, verified that ReaR aborts mkbackup instead of displaying a warning message and continuing
  3.  added nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )` in the rescue system, verified that ReaR displays a prominent warning during mkrescue before continuing and aborting later at a different place
  4. added  `BACKUP_INTEGRITY_CHECK=1` and a nonsensical rsync option `BACKUP_RSYNC_OPTIONS+=( -M--nonsense )` in the rescue system, verified that ReaR displays a rsync error and aborts during mkrescue instead of continuing and aborting later at a different place

  Against CentOS 8:
full backup and restore using rsync over ssh

* Brief description of the changes in this pull request:
Cleanups of rsync code to use better variable names and local variables, stop using `StopIfError`, use better redirections etc.
Fix a problem with rsync error detection that caused rsync errors during backup restore to be ignored (fixes #2612). Now a warning is displayed and if `BACKUP_INTEGRITY_CHECK` is true, it is elevated to an error and ReaR aborts.
Detect errors during rsync backup: they were reported only as warnings, which is risky, because if nobody reads them, one could easily end up with a broken backup (therefore impact High).

### CODE REVIEW

**Comment by pcahyna** [comment]
Note: this intentionally reverts commit 3548430302cef3a8445de970eb763da33d9f6e8e of PR #2011. I found that the intent of the commit was wrong and the code was not correct.

File: usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh [hunk 1]
```diff
@@ -1,3 +1,5 @@
+local backup_prog_rc
+
 [ -f $TMP_DIR/force.autorelabel ] && {
 
 	> "${TMP_DIR}/selinux.autorelabel"
```
Comment (jsmeix) [inline usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh:5]: @pcahyna 
a question out of curiosity:
Could you explain what code like `> .../selinux.autorelabel` is meant to do?
I am not a SELinux user (at least I don't use it knowingly)
so for me that code look rather obscure.
My guess is that creating an empty `selinux.autorelabel` file
in whatever "right" directory triggers something - but what?

**Review by jsmeix — APPROVED** [review]
From plain looking at the code it looks OK to me
but I did not actually test anything myself here.

**Comment by jsmeix** [comment]
@rear/contributors
please have a look if time permits
and if there are no objections from you
I would like to merge it tomorrow afternoon.

File: usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh:5]: It triggers selinux relabeling after boot of the restored system. The primary source of the SELinux information on files is some database that assigns contexts to file paths. But this information is not directly used by the kernel, the kernel checks the `security.selinux` extended attribute on the given file. So if the extended attributes get out of sync with the database (this can happen because of restoring a backup that does not contain this information), some tool needs to set the extended attributes again on all the files that should have them, and this is called relabeling.

Now, in ReaR, it is hard to understand how it is done, because there are several files to trigger it, with a similar functionality, like `force.autorelabel` and `selinux.autorelabel` and it is not obvious how they interact. I also don't see why it has to be backup method specific, because it means that every backup method needs to reimplement it (most likely most of them need it). I think having it in output instead of backup, like the bootloader information and disk layout, would be cleaner. I have not investigated much because I am afraid it will be another can of worms.

Comment (gdha) [reply usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh:5]: The `selinux.autorelabel` is an old flag file to trigger relabeling the files with SELinux after the restore happened. It was meant only for internal backup mechanism like tar and rsync. External backup flows should have implemented the restore of the SELinux labels by their software (we just don't care about these flows as we are not responsible of the backups made by external backup software).
By default (for internal backup flows) we turn off selinux during the backup procedure. However, we hope that 10 years later tar and rsync would have been enough involved to make backups with the keeping the label structure, no?

**Review by gdha — APPROVED** [review]

File: usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh (hunk 1 above)
Comment (pcahyna) [reply usr/share/rear/backup/RSYNC/GNU/Linux/620_force_autorelabel.sh:5]: > External backup flows should have implemented the restore of the SELinux labels by their software

I am not at all sure that external backup software is able to save and restore this kind of metadata. That's why I have thought that it might be better to implement relabeling generally in output. But maybe I am too pessimistic.

> By default (for internal backup flows) we turn off selinux during the backup procedure. 

I am curious why is it needed to turn off selinux during the backup procedure. Even if the backup tool does not have the support for storing selinux metadata, I would not expect that having selinux on makes the problem worse, or does it?

> However, we hope that 10 years later tar and rsync would have been enough involved to make backups with the keeping the label structure, no?

I suppose so, but I will need to test this.

**Comment by jsmeix** [comment]
@pcahyna 
thank you for your rsync code cleanup and your various fixes!
